cds-snc/digital-canada-ca

_includes/cds/team-listing.html

This was causing email addresses to get prefixed with a `%20` if the user clicked the link or copied the email address from the link.

Removed space prefix from mailto: URIs

---

_sass/cds/_base.scss

On small screens the heading (`h1, .h1`) displays better with `padding` instead of `margin` so that the box model does not extend to the right of the viewport. At the moment, some text (on the home page) is truncated on the right side of the viewport on small screens.
1. Open `digital.canada.ca` in Chrome
2. Open dev tools
3. Toggle device toolbar (cmd + shift + m) (macOS)
4. Set to a small screen size (anything below tablet size)

Fix heading layout on small screens

---

_pages/en/work-with-us.html

Super tiny thing: “Why you want to work with us?” -> “Why do you want to work with us?”
Alternatively, the fix might be to drop the question mark (the French version lacks the question mark).

Fix typo on work with us

---

_posts/en/2018-01-09-hiring-at-cds.md

* Uppercase Interchange: “interchange” -> “Interchange” for one instance.
* “Federal Student Work Exchange Program” -> “Federal Student Work Experience Program”

Fix typos in hiring blog post

---

_includes/cds/disqus-embed.html
_pages/en/engagement-report/beginning-the-conversation-full.html
_pages/en/engagement-report/beginning-the-conversation-summary.html
_pages/fr/engagement-report/commencement-de-la-conversation-complet.html
_pages/fr/engagement-report/commencement-de-la-conversation-sommaire.html
_sass/engagement/_headers.scss
_sass/engagement/_print.scss

At long last - print-friendly updates for the [Engagement Report](https://digital.canada.ca/beginning-the-conversation/full-report/).
Previous print output:
New print output:
Includes fixes to headings, layout, theme colours, and overall font-size, line-height, and margins for text elements.

Print friendly fixes

---

_layouts/cds/base.html

I noticed in [the latest blog post](https://digital.canada.ca/2018/03/26/automated-testing-blog/) that the `<strong>` tag in the post title was rendering to the browser title in plaintext. The `<title>` element [doesn’t support tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title), so I used the `strip_html` filter to take them out.
Before:
After:
The `<strong>` also appears in social media embeds, so it seems worth removing.

Remove HTML tags from <title> in base layout

---

index-fr.html
index.html

Unclear if this was put in orginally for safety of dynamic parsing... If someone has write access to the repo, this is probably going to be the least of our concerns.
This commit is to fix the visibility of <strong>not</strong> on the main page in the 'more blog posts' auto generated tiles that @szinck1 reported on slack earlier.

Remove 'escape' templating logic from post.title to avoid stripping html tags

---

_includes/cds/team-listing.html

The exec section of the team page didn't have the logic to add GitHub links to people's profiles. Added so I can claim what little cred I have left in that department.

added github logic to exec section

---

Gemfile.lock

addresses the security warning regarding nokogiri 1.8.1

updated dependencies

---

_data/team.yml

We had joined the CDS team
To be on the site was our dream
Our photos were there
(We both have great hair)
But @liam-davidson had run out of steam [when adding us to the site]
I think this is everyone, might have missed some ;)

Add forgotten team members

---

_pages/en/blog.html
_sass/cds/_base.scss

Font-size for any <a> tag was staying the desktop size because it wasn't explicitly set to scale like the rest of the fonts. 
Also removed the "By" from the author name on blog page. It was already gone on French, so only did on English.

Fixed scaling on font-size for links. 

---

_pages/en/chief-of-staff.html
_pages/en/head-of-engineering.html
_pages/en/head-of-talent.html
_pages/en/work-with-us.html
_pages/fr/chef-de-cabinet.html
_pages/fr/chef-de-l-ingenierie.html
_pages/fr/responsable-du-talent.html
_pages/fr/travaillez-avec-nous.html

Comms needed the Head of Talent job posting added. Made a page for this, and then created another link on the Work With Us page. 
Also added descriptions to the existing job postings (for SEO).

Added Head of Talent page and related link to the Work With Us page

---

_includes/cds/en/mailing-list.html
_includes/cds/fr/mailing-list.html
_posts/en/2018-06-12-setting-users-up for-success-with-content-design.html
_posts/fr/2018-06-12-donner-aux-utilisateurs-les-moyens-de-réussir.html
_posts/fr/2018-06-14-parlons-de-l’expérience-utilisateur.html
_sass/cds/_components.scss
_sass/cds/_sections.scss
index-fr.html
index.html

Removed the youtube video from the homepage (as discussed with Comms). 
Additionally: 
- Changed beta banner to blue on Product page. 
- Added description text to blog posts that were missing it. 
- Removed placeholder on email input field (home and contact includes)

Removed youtube video on home page & a few small changes.

---

_pages/en/blog.html
_pages/fr/blogue.html
_posts/en/2018-06-14-lets-talk-user-experience.html
_posts/en/2018-08-17-lexicon.md
_posts/fr/2018-06-14-parlons-de-l’expérience-utilisateur.html

Tag team with @liam-davidson, this addresses #290 to switch the preview text to use the metadata description field instead of the post.excerpt (first paragraph etc.).

Blog description previews

---

assets/sass/cds/_layout.scss

Reverts changes in 18fddca now that International Day of Persons with Disabilities 2018 is complete. <https://github.com/cds-snc/digital-canada-ca/pull/418>
Thanks @brdunfield for catching the .home / .accueil classes that I missed on the first edit!

Revert purple homepage header back to default colours

---

content/en/products/products/secure-web-tool.md
content/fr/products/products/secure-web-tool.md

This PR adds a link to the companion documentation for _Track web security compliance_. 
[English url](https://cds-snc.github.io/track-web-security-compliance/)
[French url](https://cds-snc.github.io/track-web-security-compliance/accueil/)
Looks like: 
If there's another plan to better incorporate companion documentation on the product page, or if you don't think it should go there because it's not consistent with all products, no hard feelings on rejecting this! 
cc @rossferg ?

Adding documentation links

---

config/_default/config.yaml
content/en/our-team.html
content/fr/our-team.html
i18n/en.yaml
i18n/fr.yaml

Includes English + French version changes to the following:
ENG:
- Content changes to main paragraph of 'Meet the team' page
- Changed Our team to Meet the team. (Menu bar and page title)
- Changed Key Contacts to Key contacts. (Heading above the management photos)
- Changed Meet the Full Team to The full team. (Heading above the full team’s photos)
FR:
- Content changes to main paragraph of 'Rencontrez l’équipe' page
- Changed Notre Equipe to Rencontrez l’équipe. (Menu bar and page title)
- Changed Contacts to Contacts principaux. (Heading above the management photos)
- Changed Rencontrer l'équipe to Toute l’équipe. (Heading above the full team’s photos)

Content changes to "Meet the team" page

---

content/en/blog/posts/the-policy-pieces-for-conducting-research-with-vac.md
i18n/fr.yaml

Blog post: The policy pieces for conducting research with vac.md
*there wasn't a line for thumbnail image so I added this:
thumb: /img/cds/tim-swaan-45717-unsplash.jpg

fixed blog post thumbnail image on Blog post

---

assets/sass/cds/_mixins.scss
assets/sass/cds/_nav.scss
config/_default/config.yaml
i18n/en.yaml
i18n/fr.yaml

*this is an updated version of a previous PR (#699). this good copy features the updated logo changes, which #699 did not. 
Made content changes to the website's menu headings. These changes ended up making the menu width longer, so the following changes are meant to address that:
Change to the actual menu content on files: config.yaml, en.yaml, fr.yaml
As a result of the above menu content changes on files, new styles are meant to bring the Waffle menu on earlier. Made the following style changes to sass files:
_mixins.scss (made 3 new mixins to address custom screen width breaks)
_nav.scss (replaced some pre-existing screenwidths like tablet and mobile_only with those mixins. Also centered the menu to middle of the screen in english and french)

UPDATED VERSION of pr #699: content + style changes to address Header Menu updates before the budget

---

assets/sass/cds/_mixins.scss
assets/sass/cds/_nav.scss

Added + reduced pixels for two mixins to address a bad breakpoint on menu header:
- @mixin logo_break (changed from min-width 1200px to 1210px)
- @mixin menu_break (changed from max-width 1200px to 1209px)

Quick fix for breakpoint issue on header menu

---

content/en/blog/posts/attracting-and-recruiting-top-talent-with-a-little-help-from-our-friends.md
content/fr/blog/posts/attirer-et-recruter-les-meilleurs-talents-avec-un-petit-coup-de-main-de-nos-amis.md

Removed the "thumb" and "process" fields for English / FRench version of blog post that went up this AM ("Attracting and recruiting top talent, with a little help from our friends") to address issue of thumbnail image not showing...

removed Thumb and Processed fields for English and French

---

content/en/blog/posts/attracting-and-recruiting-top-talent-with-a-little-help-from-our-friends.md
content/fr/blog/posts/attirer-et-recruter-les-meilleurs-talents-avec-un-petit-coup-de-main-de-nos-amis.md

Added this field to French + English blog posts: 
thumb: /img/cds/beetletoy.jpg

second try at fixing missing thumbnail on blog post

---

layouts/shortcodes/roadmap/div.html

We had a Hugo 0.54 vs 0.55 issue, causing the Markdown to not render in the live site. Oops!
See Hugo 0.55 changelog: https://gohugo.io/news/0.55.0-relnotes/

Fix Markdown rendering in roadmap

---

content/en/cppd-research.html
content/fr/cppd-research.html
i18n/en.yaml
i18n/fr.yaml

French page has a few phrases that need translation. Specifically, those with `TRADUIRE` in them, in these files:
- `content/fr/cppd-research.html`
- `i18n/fr.yaml`
Also, the page title (“Canada Pension Plan Disability Benefit Research” in English) breaks poorly across three lines, because it’s so long and the font size so big. A shorter title and/or a CSS tweak to accommodate the title would be 👌 
Page links:
- EN: https://digital-canada-ca-pr-838.herokuapp.com/cppd-research/
- FR: https://digital-canada-ca-pr-838.herokuapp.com/fr/cppd-research/

Draft for ESDC recruitment page

---

content/fr/blog/_index.md
content/fr/our-team.html
content/fr/products/_index.html
content/fr/what-we-do.html
content/fr/work-with-us/_index.html

It was just missing translation that broke the logic for this .active CSS class assignment- in french pages it was looking for the english section titles names instead.  
The navigation should now work as expected.

Added the french section navigation highlight fixes

---

layouts/partials/social-links.html

The Outreach team has decided to no longer publish blogs in the CDS/SNC Medium accounts. As a result, we this PR takes the Medium social icon off the bottom contact banner.

Removed Medium social icon from website's bottom contact banner

---

content/fr/blog/_index.md
i18n/fr.yaml

This CL fixes the translation page for the 'Read The Blog' link on the French site.

Fixup Read The Blog on French site

---

i18n/en.yaml
i18n/fr.yaml
layouts/index.html

The "Read all our blog posts" text is missing on the homepage, so this PR adds that line on the English + French sections. 
https://trello.com/c/m6xGyd6P/108-the-read-all-our-blog-posts-text-is-missing-on-the-homepage

added "Read all our blog posts" text (EN + FR) to Homepage blog section

---

assets/sass/cds/_sections.scss
layouts/blog/list.html
layouts/index.html

This PR includes style changes to the Blog Page to match the design mockup: https://app.zeplin.io/project/5cb8c2c34ef04a6a787fbe65/screen/5d7961cd9cbbe89d9747bdc5
*still iterating on how to address responsive image sizes 
Trello:
https://trello.com/c/QW58G4wI/114-update-styles-for-blog-page-based-on-mockup

Update Blog Page styles based on mockup

---

layouts/blog/list.html
layouts/blog/single.html
layouts/index.html

This PR removes the comma between the month and year for blog dates in French, featured on:
- The homepage
- Blog page
- Individual blog posts
For example, dates now read as "30 août 2019" instead of "30 août, 2019"

Removed comma between month and year for French blog dates

---

assets/sass/cds/_sections.scss
layouts/section/blog.html

On the blog, in the pagination, the first page link (either **First** or **1**) is always shown with a yellow background, as if it's highlighted/selected. This doesn't seem right!
In the template it looks like there's supposed to be an `active` class added to the `<li>` corresponding to the currently active page, but the `if eq` statement doesn't check the right thing. 
In the CSS, yellow background is applied to the first `.pagination` child: https://github.com/cds-snc/digital-canada-ca/blob/11be118d10ca58d8337b82a7bab8754167e0e736/assets/sass/cds/_sections.scss#L975
Meanwhile, the `active` class seems to just [add an invisible line through the middle of the element](https://github.com/pt8o/digital-canada-ca/blob/088e3402eade013a19f80ceafb65058648793ab5/assets/sass/cds/_sections.scss#L984 …

Fix: in blog pagination, apply 'active' style to the link for the currently active page

---

assets/sass/cds/_sections.scss
content/en/_index.html
content/en/tools-and-resources/guide-interviewing.html
content/en/tools-and-resources/tools-and-resources/branch-review.md
content/en/tools-and-resources/tools-and-resources/bundle-tracker.md
content/en/tools-and-resources/tools-and-resources/dependancy-checker.md
content/en/tools-and-resources/tools-and-resources/evaluation-framework.md
content/en/tools-and-resources/tools-and-resources/github-actions.md
content/en/tools-and-resources/tools-and-resources/guide-interviewing.md
content/en/tools-and-resources/tools-and-resources/guide-usability-testing.md
content/en/tools-and-resources/tools-and-resources/log-driver.md
content/en/tools-and-resources/tools-and-resources/pii-tracker.md
content/en/tools-and-resources/tools-and-resources/security-goals.md
content/en/tools-and-resources/tools-and-resources/time-to-interactive.md
content/fr/tools-and-resources/guide-interviewing.html
content/fr/tools-and-resources/tools-and-resources/branch-review.md
content/fr/tools-and-resources/tools-and-resources/bundle-tracker.md
content/fr/tools-and-resources/tools-and-resources/dependancy-recommendations.md
content/fr/tools-and-resources/tools-and-resources/evaluation-framework.md
content/fr/tools-and-resources/tools-and-resources/github-actions.md
content/fr/tools-and-resources/tools-and-resources/guide-interviewing.md
content/fr/tools-and-resources/tools-and-resources/guide-usability-testing.md
content/fr/tools-and-resources/tools-and-resources/log-driver.md
content/fr/tools-and-resources/tools-and-resources/pii-tracker.md
content/fr/tools-and-resources/tools-and-resources/security-goals.md
content/fr/tools-and-resources/tools-and-resources/time-to-interactive.md
layouts/section/tools-and-resources.html
layouts/tools-and-resources/list.html

This PR includes the following changes:
- Updating header styles for cards on Tools and Resources page to resemble Product cards
- Tools and resources cards now have phase labels
- Changed title and blurb in Tools and resources page from "Guide to interviewing" to "Guide to research interviewing"
- on Homepage: moved "Learn more" link to below paragraph for accessibility reasons

Style fixes: Homepage + Tools & Resources page

---

assets/sass/cds/_sections.scss
layouts/index.html

This PR includes the following changes:
- Moved two buttons (Meet the team and Apply now) featured in the Team section of the Homepage to the left
- Added margin-top styles to "...but we need your help" heading to provide more spacing between elements

Homepage team section button styles

---

package-lock.json
package.json

Remediation
Upgrade serialize-javascript to version 2.1.1 or later. For example:
"dependencies": {
"serialize-javascript": ">=2.1.1"
}
or…
"devDependencies": {
"serialize-javascript": ">=2.1.1"
}

[security-patch] serialize-javascript upgrade to 2.1

---

layouts/section/join-our-team.en.html
layouts/section/partnerships.html
layouts/tools-and-resources/list.html

This PR includes some additional IDs and classes assigned to the following elements (to track specific metrics through Google Tag Manager and Google Analytics):
- Added the ID "partnerships-contact-us-link" to "contact us" link on Partnerships page
- Added class of "tool-resource-link" to individual Tools/Resources title links
- Added class of "job-posing-link" to individual job postings on Join our team page

added ids and classes to elements for Google Tag Manager

---

assets/sass/cds/_base.scss
assets/sass/cds/_sections.scss
layouts/section/join-our-team.en.html
layouts/section/join-our-team.fr.html
layouts/section/meet-the-team.html
layouts/section/partnerships.html
layouts/section/tools-and-resources.html

This PR adds the yellow newsletter subscribe banner (currently on on the homepage) to the following pages:
- Partnerships
- Tools and resources
- Join our team
- Meet the team

added Newsletter Banner to webpages

---

i18n/fr.yaml

This PR includes the following updates on the FR Partnerships page:
- Change “satisfaire les” for “répondre aux”
- Change “mise en ligne” for “mise en service” (3 times)
- Change “SNC” for “Service numérique canadien” (3 times)
- Change “savois” for “savoir”

French updates on Partnerships page

---

content/fr/blog/posts/congé-civique-intégrer-les-talents-du-privé-dans-le-secteur-technologique-public.md

This PR changes "congé civique" for "congé pour fonctions civiques"

French vocabulary update on civic leave post

---

config/_default/config.yaml

With the new redesign of our Blog list page, there's a gap on the bottom right (since 5 posts are displayed per page).
This PR changes the display number from 5 to 6 blogs per page.

Changed display number for Blog list page from 5 to 6

---

util/processBlogImages.js

This PR adds a medium image size to the blog image process script
I have left the line commented out to avoid generating the images / altering the blog posts with this PR
See:
https://github.com/cds-snc/digital-canada-ca/compare/add-medium-image-size?expand=1#diff-a052db16441ce3bc43762cac0640d0f3R91
Adjust the image size to whatever is a good fit (doesn't have to be square). Uncomment the line.
Run 
```
npm run build
```
Will generate the new images.
To update the blog posts with the new Front Matter meta comment out the `if (data.processed) {` line
https://github.com/cds-snc/digital-canada-ca/compare/add-medium-image-size?expand=1#diff-a052db16441ce3bc43762cac0640d0f3R23

Prep for medium image size

---

assets/sass/cds/_sections.scss

After the redesign of our blog list page, some text summaries have been [sliding outside of their containers](https://github.com/cds-snc/digital-canada-ca/issues/1268). 
This PR adds a few style rules to Author and Summaries of each blog tile to limit the lines that each block will preview (in both desktop and mobile view).

Added text limit to blog list summaries 

---

assets/sass/engagement/_roadmap.scss

Fixes the paragraph line height on the Roadmap pages (English and French) when printed or saved as PDFs. Thanks! 😄

Minor fix to roadmap print layout

---

content/en/products/products/help-canadians-access-the-cpp-disability-benefit.md
content/en/tools-and-resources/_index.html
content/fr/_index.html
content/fr/products/products/aider-les-canadiennes-et-les-canadiens-à-recevoir-des-prestations-d’invalidité-du-rpc.md
content/fr/tools-and-resources/_index.html
i18n/en.yaml
i18n/fr.yaml

Added long form for CDS, SNC, CPP and RPC acronyms
-Homepage
-Partnerships page
-Tools and resources page
-CPPD product card

add long form for acronyms

---

assets/sass/cds/_layout.scss
content/en/tools-and-resources/digital-reading-list.html
layouts/engagement/default.html
layouts/section/blog.html

Fix the following accessibility errors:
UL and OL must only directly contain LI, SCRIPT or TEMPLATE elements
OBJECT elements must have alternate text
Links must have discernible text
Elements must have sufficient color contrast

A11y fixes

---

assets/sass/cds/_layout.scss
content/en/covid-health-research.html
content/fr/covid-health-research.html

This PR includes content updates to EN + FR research recruitment pages for:
- https://digital.canada.ca/covid-health-research/
- https://numerique.canada.ca/recherche-sante-covid/

Update to Covid Health Research recruitment pages

---

static/admin/config.yml

Linkedin ended up with github for the name, which is not only incorrect, but a duplicate, causing the CMS to error

Fix duplicate field name in datafiles

---

assets/sass/cds/_sections.scss
layouts/section/join-our-team.en.html
layouts/section/join-our-team.fr.html

This PR includes the following changes to the Join our Team page:
- Adding responsive width styles to individual job postings 
- Fixing gap in the first column of individual job postings of English Join our Team page

Fix gap between job posts on Join our Team page

---

static/admin/config.yml

Currently, Hugo strips out raw HTML from .md files. This config change tells the renderer (Goldmark) to allow the raw HTML to stay in the file when rendered. This is necessary to view things like tables within blog posts.

Allow raw HTML in markdown files to be rendered

---

assets/sass/cds/_variables.scss
assets/sass/engagement/_settings.scss
layouts/section/meet-the-team.html

This affects images that have already been ported to the s3 bucket, so far:
- Team images
- Beginning the conversation page
This is needed so we can make the s3 bucket private, as per https://github.com/cds-snc/site-reliability-engineering-internal/issues/91

Update images to point to new cloudfront url instead of s3 bucket directly

---

data/team.yml
layouts/section/meet-the-team.html

When I migrated team data to Strapi, I removed the "middleman" team.yml file. Which worked well, except that when a change is made in strapi, the site needs to be rebuilt and deployed. The PR bot has no way to detect a change since no files are being changed.
So I'm restoring the team.yml file so that changes can be easily detected and rebuilt through existing pipelines.

Restore team.yml so PRs will work for team data

---

content/en/blog/posts/learning-to-make-twitter-content-more-accessible.md
content/fr/blog/posts/-apprendre-à-rendre-le-contenu-sur-twitter-plus-accessible.md

The PR bot is selecting a thumbnail that is too small for the size of our actual thumbnails, leading to blurry images.
I'm bumping up to the next larger format for the most recent blog post. I will update the PR bot shortly!

Change which image is selected for thumbnail on recent blog post

---

.github/workflows/a11y_tracking.yaml

This PR fixes the A11Y tracker CI because this is an older repo and still uses the older non- `main` branch convention.

fix: a11y tracker CI

---

layouts/_default/single.html

Previously, Hugo would complain about this multiple times when building the site with the following warning message:
> WARN 2021/03/26 12:44:19 found no layout file for "HTML" for "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
This removes these warnings.
There are still a couple outstanding warnings, but they should be addressed whenever #2052 is.

Add an empty layout file to cut down on Hugo warnings when building the site

---

layouts/index.html
layouts/section/partnerships.html
layouts/section/tools-and-resources.html

* Fix .URL -> .Permalink warning
* Fix .Dir -> .File.Dir warning
Issue #2052
This touches on the index, partnership and tools-and-resources pages so those are the one's you'll want to verify.
The .File.Dir zero object warning remains, I've been unable to figure
out how to fix it. It's currently triggered in each of the 3 places we
use .File.Dir.

Fixup a couple Hugo warnings.

---

layouts/_default/baseof.html
layouts/a11y/default.html
layouts/engagement/default.html
layouts/roadmap/baseof.html

Lighthouse was showing an error about the skip to main content `li` tag
not being contained in a `ul`. The a11-tools-query gave a bit more
context that the `ul` should not have a `navigation` role (fixing both
the invalid `navigation` role on the `ul` and the `li` missing a
non-role'd parent).
This change uses the same `ul` as is used on Canada.ca and to wrap the
`ul` in a `nav` similar to Canada.ca.
Fixes #2129
This is changing the global templates for a bunch of pages, so probably a good idea to check around on a few random pages to make sure everything is OK.

[a11y] Fixup skip to main content list tag.

---

i18n/en.yaml
i18n/fr.yaml
layouts/section/partnerships.html

Updating the "Contact Us" button link on the Partnerships page to the following intake forms:
- English link: https://forms-formulaires.alpha.canada.ca/id/45
- French link: https://forms-formulaires.alpha.canada.ca/fr/id/45

Updating Contact Us link on Partnerships page

---

assets/sass/engagement/_settings.scss

This PR fixes a warning which appears as the declaration and setting of
a variable `!global` is deprecated. This PR pre-declares the variable at
the top of the file allowing it to be made global later.
Issue #2052

Pre-declare variables before setting global.

---

assets/sass/cds/_sections.scss
layouts/products/list.html
layouts/tools-and-resources/list.html

This PR changes the headings of the product cards to use h1/h2 instead
of h4/h5. In the latter case, the homepage would have headings h1, h2,
h4, h5 which causes an accessibility warning.
This PR changes the cards to use h1/h2 as the headings are inside a
section and updates the stylings to match. Most of the divs have been
removed as the cards still appear to format correctly without all the
tag nesting.
Fixes #2288

Change card headings for better accessibility.

---

layouts/index.html

It seems with newer Hugo the main page needs to use `.Site.Pages`
instead of `.Pages` in order for the page content to show up.
This seems to also pull in the folder as a data item, it's fine for the
products as they have an `onhomepage` filter. For the blog posts I added
in a filter to make sure there was a `author` tag in order to filter
out the folder.
Issue #2052

Fix missing content with new Hugo.

---

assets/sass/cds/_sections.scss
layouts/products/list.html
layouts/tools-and-resources/list.html

This reverts commit 0b9268ab70b91a3e1aa8bfff9afb3a1199fd2a3d.
When looking at the changes it was decided it was better to skip a
header level on the main page then to have duplicate header levels which
happened with the fix. We were unable to get the current system to take
the header level as a template parameter.
This will go back to the backlog and we'll probably need to either
duplicate the list template, or change the site so the header levels are
the same when this template gets included.
Issue #2288

Revert "Change card headings for better accessibility. (#2322)"

---

.circleci/config.yml
.github/workflows/a11y_tracking.yaml
content/en/tools-and-resources/digital-reading-list.html
content/fr/tools-and-resources/digital-reading-list.html
layouts/roadmap/default.html

The primary branch has been changed to `main`. This PR updates various
points in the repo which use the old branch name.
Issue #2249

Update references to old primary branch.

---

layouts/partials/mailing-list.html

remove overlay classes from all newsletter link
This was preventing the link from properly opening, and the classes are unnecessary for styling.
---
Make sure the "Read all newsletters" link on the yellow Subscribe to Newsletter box works properly when clicked.

fix all newsletter link

---

CONTRIBUTING.md
README.md

Documentation on how to update content on the website in the post Strapi world has been poor. Collabbing with @victoriachanimal to fix this!
This PR adds a CONTRIBUTING.md file, which explains which content is managed in the CMS, and how to go about updating it (since PRs alone will not 'stick' if the content is managed by Strapi).
Putting up a first draft here, while Vic is away, hopefully will finalize and send out for translation later this week!

Add draft for Contributing guidelines explaining how to update CMS managed content

---

content/fr/blog/posts/choisir-nos-projets.md
content/fr/blog/posts/concevoir-pour-le-canada.md
content/fr/blog/posts/lancement-d’un-service-alpha.md
content/fr/blog/posts/parler-numerique-en-francais.md
content/fr/blog/posts/pourquoi-canada-a-besoin-service-numerique.md
content/fr/blog/posts/recherche-dirigeant-principal-du-service-numerique-canadien.md
content/fr/blog/posts/retrospective-sur-lapi-denerguide.md

English and French translation keys don't match for some of our early blog posts (eg. https://digital.canada.ca/2017/08/03/why-canada-needs-a-digital-service/), or there is an extra "/" at the end of some French translation keys.
This PR matches the translation keys for several of our past blog posts so that the language toggle appears for both languages.

Matching English and French translation keys for blog posts

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.gitignore

Adds a devcontainer that will allow us to have a consistent environment.
Uses the default node 14 image and adds node 10 using nvm.
If you want to do dev in node 10 hten you should run `nvm use 10` upon
startup

feat: add devcontainer

---

i18n/en.yaml
i18n/fr.yaml
layouts/_default/baseof.html
layouts/partials/menu.html

- Provides unique aria-labels to both Nav landmarks on the page this is related to success criteria 1.3.1 https://www.w3.org/TR/2008/REC-WCAG20-20081211/#content-structure-separation-programmatic
- Moves the index block into the main landmark so that we don't have content not inside a landmark.
We may need some review to see if the above is okay, I'm mainly thinking of moving the index block into the main landmark we may want to add a second main landmark and provide them with unique names.
This should have no real changes to the rendering of the page and should only affect those using screen readers. I will need a french speaker/content designer to review the new text to see if it makes sense as I just deepl and some google searches for translating.
This changes the number of a11y issues …

fix: landmark issues found by axe

---

layouts/products/list.html

Adds an aria label to the View this product links that lets screen
readers know what page they will go to.
To simplify translation I'm simply using the title of the card so we
don't have to worry about handling products that start with vowels and
articles if we want to use View the.
This may need some content design thinking to determine the best text we
want to use for those folks viewing the site with screenreaders.
Closes #2415

feat: add an aria-label to "View this product"

---

i18n/en.yaml
i18n/fr.yaml
layouts/a11y/default.html
layouts/engagement/default.html
layouts/partials/footer.html
layouts/roadmap/baseof.html

- Adding labels to the `nav` landmark in the footers, if there is an H2
I added an aria-labelledby and if there wasn't I added the text
aria-label the text for that label should be reviewed by a content
designer to make sure it makes sense but can probably be done later as
footer links is generic enough it should work for now.
- Added labels to the skip links in the a11y handbook, the engagement
page and the roadmap.

fix: missed nav labels

---

layouts/engagement/default.html

This fixes a serious a11y issue. The fix was to copy the aria label from
the fip.html page. I didn't replace the FIP in the engagement html
because I didn't know why it wasn't using it in the first place and
wanted to make sure the change was minimal.

fix: adds a label to an svg object

---

layouts/section/job-posting.en.html
layouts/section/job-posting.fr.html

This is just a deque best practice fix.
This fixes the aria-allowed-role issue found in grouped validations (I'd
link to it but I can't :sad:)
This role is redundant as the element is already a role and so does not
need another role attached to it.
MDN information on Role = Form
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Form_Role
Deque University Issue
https://dequeuniversity.com/rules/axe/4.1/aria-allowed-role

fix: remove redundant role on form

---

content/en/tools-and-resources/guide-interviewing.html
content/fr/tools-and-resources/guide-interviewing.html

This PR changes the `h4` headers on the guide-to-interviewing pages to
`h3`s in order to make them sequential.
This fixes up the heading-order accessibility violation [1].
[1]: https://a11y-tools-query.herokuapp.com/violations/cds-snc%2Fdigital-canada-ca/a71ef9fda80a0b17a723c306bfe8f7776c9e757f#violation6

Update guide-to-interviewing headers.

---

content/en/tools-and-resources/evaluation-framework.html
content/fr/tools-and-resources/evaluation-framework.html

This PR changes the `h4` headers to `h3` headers on the valuation
framework to make them correctly increase in order.
This fixes the `heading-order` accessibility violation [1].
[1]: https://a11y-tools-query.herokuapp.com/violations/cds-snc%2Fdigital-canada-ca/a71ef9fda80a0b17a723c306bfe8f7776c9e757f#violation9

Fixup heading order on evaluation framework pages.

---

i18n/en.yaml

On the Roadmap-2025 and the Beginning the Conversation page there is a
header in the footer using the `about-this-site` translation key. This
key exists in the French YAML, but not English.
This causes an empty-heading [1] violation for the English version of
these pages.
[1]: https://a11y-tools-query.herokuapp.com/violations/cds-snc%2Fdigital-canada-ca/a71ef9fda80a0b17a723c306bfe8f7776c9e757f#violation2

Add missing about-this-site English translation key.

---

layouts/blog/single.html

This PR changes the blog navigation `h5`s to `divs` to fixup the issue
with heading-order violations [1].
[1]: https://a11y-tools-query.herokuapp.com/violations/cds-snc%2Fdigital-canada-ca/a71ef9fda80a0b17a723c306bfe8f7776c9e757f#violation3

Change pagination to divs from h5s.

---

content/en/tools-and-resources/guide-usability-testing.html
content/fr/tools-and-resources/guide-usability-testing.html

This fixes the header-order issue in the guide to usability testing [1].
[1]: https://a11y-tools-query.herokuapp.com/violations/cds-snc%2Fdigital-canada-ca/a7b90b63ebde8c9953707e9c476de6843c871482#violation1

Fixup heading order in guide to usability testing

---

.circleci/config.yml

If there is a hugo cache lying around, ignore it when running a build.

Ignore hugo cache in circle CI build.

---

assets/sass/cds/_components.scss

The blogpost title and pretitle were yellow and white respectively and
this caused serious a11y issues regarding contrast, this sets both of
them to black and so will fix the issue.
Fixes #2437

fix: set title and pretitle of blogpost to black

---

layouts/index.html
layouts/partials/partnerships_product_item.html
layouts/section/partnerships.html
layouts/section/products.html
layouts/section/tools-and-resources.html
layouts/tools-and-resources/list.html

This PR duplicates the card template on the partnerships page and then
sets the correct `h` values for the various usages. This should
hopefully fix the flake seen in the html proofer.

Remove safeHTML hack and use duplicate template.

---

assets/sass/cds/_components.scss
assets/sass/cds/_sections.scss
layouts/section/job-posting.en.html
layouts/section/job-posting.fr.html

Issue with the alignment of the Job Postings Page. Mistakenly though the content was slightly aligned to the left. Content is centered. Also fixed up multiple labels issue

Content alignment and multiple labels fix

---

assets/sass/cds/_sections.scss
layouts/section/job-posting.en.html
layouts/section/job-posting.fr.html

Browse button was not working as there was a bit of an issue with the label. Fixed browse button for FR and EN. Also removed `display: none` from the input.

fixed browse button

---

content/fr/website-usability-testing.html
i18n/fr.yaml

Updating "Apply now" button on French homepage, from "Appliquer maintenant" to "Soumettre votre candidature"

Updated French Apply now button on Homepage

---

content/en/blog/posts/how-we’re-trying-to-make-virtual-onboarding-better.md
content/en/careers/_index.html
content/en/careers/positions/executive-assistant.md
content/en/careers/positions/senior-front-end-software-developer.md
content/en/careers/positions/technical-support-developer.md
content/en/careers/positions/translator-content-coordinator.md
content/en/join-our-team/index.html
content/en/join-our-team/positions/executive-assistant.html
content/en/join-our-team/positions/senior-front-end-software-developer.html
content/en/join-our-team/positions/technical-support-developer.html
content/en/join-our-team/positions/translator-content-coordinator.html
content/fr/blog/posts/améliorer-l’intégration-des-nouveaux-employés-en-période-de-télétravail.md
content/fr/careers/_index.html
content/fr/careers/positions/adjoint-e-de-direction.md
content/fr/careers/positions/développeur-de-soutien.md
content/fr/careers/positions/développeur-principal-de-logiciels-frontaux.md
content/fr/careers/positions/traducteur-traductrice---coordonnateur-coordonnatrice-de-contenu.md
content/fr/join-our-team/index.html
content/fr/join-our-team/positions/adjoint-e-de-direction.html
content/fr/join-our-team/positions/développeur-de-soutien.html
content/fr/join-our-team/positions/développeur-principal-de-logiciels-frontaux.html
content/fr/join-our-team/positions/traducteur-traductrice-coordonnateur-coordonnatrice-de-contenu.html
content/fr/rejoindre-notre-equipe/index.html
layouts/partials/404.en.html
layouts/partials/404.fr.html

We were running into issues where anything related to /work-with-us/ or /join-our-team/ would lead to a 404 page. This will now redirect to /careers/ for both EN or FR.
Also fixed the "apply now" link in the 404 page to redirect to the careers page.
This also reverts the aliases that were added on the MD file and created html files

fixed broken link

---

i18n/en.yaml
i18n/fr.yaml
layouts/section/meet-the-team.html

Updated heading for Senior Management to "Leadership" for EN and FR

changed management name

---

layouts/partials/menu.html
layouts/partials/search-list.html

Need to comment out the search bar functionality due to a mistake loading the scripts which is causing ti to violate Content Security Policy

commented out search

---

assets/sass/cds/_components.scss
assets/sass/cds/_nav.scss

Fixed the issue causing only the top half of the CDS Logo to be clickable. The issue was caused by the nav container blocking the bottom half of the logo. Solution was to limit the width and aligning div to the right.

fixed logo issue

---

assets/sass/cds/_sections.scss
i18n/en.yaml
i18n/fr.yaml
layouts/index.html

Regarding [Github Issue](https://github.com/cds-snc/digital-canada-ca/issues/2780), where the "Learn More" buttons could cause some accessibility issues for screen readers.
Fix just adds a visually hidden text "Learn More (about partnerships)"

added text for screen reader

---

i18n/en.yaml
i18n/fr.yaml
layouts/partials/social-links.html

Newsletters in the footer were not being redirected properly. 
This branch fixes the issue.

newsletter link fix

---

layouts/blog/single.html

Repositioned the buttons so now previous post appears on the right, next post appears on the left.
Fixed alignment issue:

changed button positioning, fixed alignment

---

assets/sass/cds/_layout.scss
assets/sass/cds/_nav.scss
i18n/en.yaml
i18n/fr.yaml
layouts/partials/fip.html
layouts/partials/menu.html

FR website was displaying the incorrect version of the CDS and GoC logo, this has been fixed. Also fixed aria-label for the CDS logo

fixed cds fr logo, aria label and fip

---

content/en/legal/security-notice.html
content/fr/legal/security-notice.html
i18n/en.yaml
i18n/fr.yaml
layouts/partials/footer-links.html

Added security notice documentation for both EN and FR.
There might be trouble viewing the deployment link in FR, so here are the screenshots:

security notice fr and en

---

content/en/a11y/how-to-make-it-accessible.md

- Fixed typo for "pointer" for line: "Content can be operated using simple inputs on a wide range of pointing devices using pinter gesture techniques"
- Addressed missing space "Hover and focus eventsshould not obscure content and should be dismissible"

Typo fixes to a11y How to make it Accessible"page

---

assets/sass/cds/_sections.scss
layouts/partials/product-suite-items.html
layouts/partials/resources-items.html

Our accessibility tracker was giving us an issue for the Guides page since our card titles were h3, there was no h2 on the page which was causing the issue.

fixed h3 accessibility issue

---

i18n/fr.yaml
layouts/partials/mailing-list.html

French newsletter banner fix:
Fixed issue causing part of the privacy notice to go underneath "Read Newsletter"
Fixed apostrophe issue.

fixed spacing issue

---

.github/workflows/remove-staging.yaml

This PR adds some better logic to tear down the preview environment. The problem happened when PRs opened and closed too quickly and functions did not yet exist. This changes the check to `function-exists` and will check for 120 seconds before timing out.

fix: preview teardown

---

.github/workflows/remove-staging.yaml

The PR changes the function exists check to a simple sleep. It seems like the call was flaky to check if a function exists.

fix: simplefy await

---

.github/workflows/generate-sbom.yaml

Add GitHub workflows to generate SBOMs and upload them
to Dependency-Track. This will allow us to have a view of all
the dependencies used by the org and their potential
vulnerabilities.
* cds-snc/platform-sre-security-support#94

feat: generate Software Bill of Materials

---

content/en/legal/security-notice.html
content/fr/legal/security-notice.html

We'd like users to be aware of the rules of engagement before we go into how vulnerabilities can be reported.

refactor: discuss rules of engagement before reporting instructions

---

layouts/section/guides.html

Changed the email address on the Guides page to cds-snc@tbs-sct.gc.ca since the previous one kept bouncing.

changed guides contact us email address

---

layouts/section/job-posting.en.html
layouts/section/job-posting.fr.html

Removing the line "in the future, occasional travel to Ottawa may be required" (in English and French) to job posting template.

Removing automated lines from job posting template

---

layouts/partials/menu.html

The menu links were causing issues on staging where clicking it would take you directly to the website. Changed from `absLangURL` to `relLangURL`

chnaged menu from absolute url to relative url

---

i18n/en.yaml

There's a small typo in the first sentence on the EN coaching and advice page. It currently reads: 
As federal public servants ourselves, we know how complicated digital service delivery in government can be. Our team of digital practioners is here to help. (changing it to should say "practitioners" instead).

Fixing typo on Coaching and advice English page

---

i18n/en.yaml

Change "sotware" to "software" under "Some of the things we can advise on" section

Fix small typo on Coaching / advice page

---

i18n/en.yaml

Changing "similiar" to "similar" under "How we can help" section

Fixed small typo on Coaching and advice (English) page

---

Dockerfile

Updated Debian Image to `buster-slim` the previous `stretch-slim` is no archived

updated to buster-slim

---

terragrunt/aws/s3/inputs.tf
terragrunt/aws/s3/outputs.tf

Changes to the outputs from the s3 module. Key and values will be used as alias and origin ID in the cloudfront module.

updates to s3 outputs

---

terragrunt/aws/cloudfront/route53.tf

Incorrect use of the hosted zone ID in the `"aws_route53_record" "cds_website_en_A"`

updated alias records

---

content/en/a11y/tools-and-resources.md

Fix typo in a11y handbook tools/resources section (English)

Fix typo in a11y handbook

---

.github/workflows/build-push.yml
.github/workflows/build-test.yml
.github/workflows/deploy-staging.yaml
.github/workflows/remove-staging.yaml
.github/workflows/tf_apply_production.yml
.github/workflows/tf_plan_production.yml

Was getting the following GitHub action error:
`The following actions uses node12 which is deprecated and will be forced to run on node16: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/`
Updated to version 3.0.1
 

updated aws credential action
