cds-snc/digital-canada-ca

- _sass/cds/_sections.scss
sizing wasn't correct on mobile
> fixed sizing in mobile

- _includes/cds/analytics.html
Thanks to SCMA Web Usability for the suggestion!
> Adding "anonymizeIp" flag to Google Analytics snippet

- _pages/en/work-with-us.html
- _pages/fr/travaillez-avec-nous.html
- _sass/cds/_sections.scss
- fixed modal windows in mobile
- fixed french accordion groups
- fixed div grid in french & english
> Mobile update

- _posts/en/2017-12-07-always-a-challenge.md
- _posts/fr/2017-12-07-toujours-un-defi.md
- typo
- add links to challenge platform
> Implement fixes from external PRs

- _posts/en/2018-02-14-a-conducting-user-research-with-NRCan.html
- _posts/en/2018-02-14-b-colocating-with-NRCan.md
- _posts/fr/2018-02-14-a-la-recherche-utilisateur-avec-RNCan.html
- _posts/fr/2018-02-14-b-travailler-dans-les-locaux-de-RNCan.md
changes to front matter to accept the case sensitivity of image names
> changes to image: to deal with case sensitivity

- _posts/en/2018-02-14-a-conducting-user-research-with-NRCan.html
- _posts/en/2018-02-14-b-colocating-with-NRCan.md
- _posts/fr/2018-02-14-a-la-recherche-utilisateur-avec-RNCan.html
- _posts/fr/2018-02-14-b-travailler-dans-les-locaux-de-RNCan.md
> change to front matter to accept trans url

- check
- serve
- serve-fr
- create cmd to run html/link checker
- clear _site cache before serving
> Build tools

- _config.yml
- _config_en.yml
- _config_fr.yml
- exclude the new cli tools (check, create-blog) from publishing
> exclude helper tools from publishing

- _posts/en/2018-03-26-automated-testing-blog.html
- _posts/fr/2018-03-26-les-tests-automatises.html
- Removing <strong> tags from the post title 
- Removing <u> tags in the opening paragraph
> Removed <strong> and <u> tags

- _data/team.yml
> Chief of stickers

- _posts/fr/2018-04-09-le-recrutement-de-notre-dirigeant-principal.md
- Modifications to the French version of Lena's April 9th blogpost.
> French modifications to Lena's Blog Post

- _posts/en/2018-04-09-recruiting-our-ceo.md
- _posts/fr/2018-04-09-le-recrutement-de-notre-dirigeant-principal.md
This PR conists of:
- Changing the Author: section from:
- "Lena Trudeau - Senior Advisior, CDS" to "Lena Trudeau, Senior Advisor, CDS" (Fr also)
> Content Fix

- _pages/en/products.html
- _pages/fr/produits.html
- Changing the Github links and removing the view product option
> product update NRCan

- _pages/fr/produits.html
Changed page title from Produit to Produits
> Produit -> Produits

- _pages/en/products.html
- _pages/fr/produits.html
- _sass/cds/_sections.scss
This PR consists of minor text changes to the Dashboard Page
> Dashboard Changes

- _posts/en/2018-04-13-reschedule-a-citizenship-appointment.html
- _posts/fr/2018-04-13-reporter-un-rendez-vous-dexamen.html
> IRCC blog date update

- _data/team.yml
Adding Aaron Snow to the team page
> Aaron Snow to Teampage

- _data/team.yml
Now that I have an extremely important & popular twitter account, I should probably link to it 🎉
> Add my own info to the website

- _pages/en/products.html
- _pages/fr/produits.html
- _sass/cds/_sections.scss
1) Updating the Product Dashboard Page:
- Adding Github Link to the IRCC project
- Adding Github Link to the VAC project
- Adding In-Flight and Past Product Categories
> Product Page Update

- _posts/en/2018-04-19-our-partnership-with-code-for-canada.md
We could probably use a spell check linter in the ci pipeline...not sure if they exist.
> Typo in  2018-04-19-our-partnership-with-code-for-canada.md

- _pages/en/work-with-us.html
> Comms Edits

- _includes/cds/en/mailing-list.html
- index.html
> Comms style edits

- _pages/fr/acc-ameliorez-notre-produit.html
Needed a dash in the email. typo.
> fixing email

- _pages/en/products.html
- _pages/fr/produits.html
> Deep-linking to specific entries on the product page

- _pages/en/products.html
- _pages/fr/produits.html
- Changing the IRCC Rescheduler Phase (On Products Page) from Alpha -> Beta
| Before | After |
|--------|-------|
|   ![screen shot 2018-05-30 at 4 45 54 pm](https://user-images.githubusercontent.com/30609058/40746694-19d805f0-6429-11e8-9583-67b57b77987f.png)  | ![screen shot 2018-05-30 at 4 45 14 pm](https://user-images.githubusercontent.com/30609058/40746711-228afee6-6429-11e8-8831-e95bbefd60fd.png)      |
> IRCC Rescheduler Phase Switch: Alpha -> Beta

- .circleci/config.yml
- _pages/en/vac-improve-our-product.html
- _pages/fr/acc-ameliorez-notre-produit.html
- check
Facebook conversion pixel javascript code for just the VAC landing pages.
> Add facebook conversion pixel for VAC recruitment landing page.

- _posts/en/2018-05-16-reducing-risk-through-continuous-deployment.md
with <https://digital.canada.ca/2018/04/24/coding-is-a-team-activity/>
> Capitalizing Jason's title for consistency

- _posts/en/2018-06-12-setting-users-up for-success-with-content-design.html
Going from English to French on this blog post page it was getting a 404 not found error, need to send to live server to test if it's fixed
> Fixed trans URL error

- _pages/en/products.html
- index.html
There was an issue where Jen's contact info was showing up twice, so I just took out the second row.
> Product page contact fix

- index.html
When I created my last branch I realized there was a weird change on my local master that screwed up the alignment of the lead paragraph
> Fixed lead-in issue that got messed up on last PR

- index.html
I accidentally made a change on my local master branch that I'm getting rid of (this will fix the lead-in alignment issue that's currently showing up on the live site as well)
> fixed issue with mistake on local master

- _includes/cds/site-menu.html
- _sass/cds/_components.scss
- _sass/cds/_layout.scss
- _sass/cds/_nav.scss
Resolved issue #200 language switcher disappears on small screens. Fixed an issue where menu icon was going offscreen on mobile. Changed the home icon styling to match the rest of the pages
> French toggle fix mobile

- _pages/en/products.html
- _pages/fr/produits.html
One of the headers was in the wrong place in the html, and it was causing the padding to be off, so I shifted it down into it.
> Shifted in-flight header on products page into a section

- _pages/en/products.html
- _pages/fr/produits.html
- _sass/cds/_sections.scss
- Fixed incorrect nesting on headers (h2 nested inside of h2) 
- Resolved a padding issue on the h2 headers
> Resolved issues with padding in the Products page 

- _pages/en/products.html
- _pages/fr/produits.html
added space between Ross and email
Capitilizaed english title
removed regulatory affairs
added link to TBS in partner name
> Cleaned up Products Page

- Gemfile
- Gemfile.lock
Updating deps to address Snyk alerts
> updated dependencies

- _pages/en/chief-of-staff.html
- _pages/en/head-of-talent.html
- _pages/en/work-with-us.html
- _pages/fr/chef-de-cabinet.html
- _pages/fr/responsable-du-talent.html
- _pages/fr/travaillez-avec-nous.html
This PR combines all of Anatole's changes into one branch! Remove links to closed oppotunities, modify page text of closed opportunities.
> Recruitment patch

- _pages/en/senior-product-manager.html
Noticed a small typo on the SPM page
> Fix small typo

- _posts/en/2018-07-17-community-driven-coding.md
> Fix typo 2 electric boogaloo

- _posts/en/2018-07-17-community-driven-coding.md
- _posts/fr/2018-07-17-codage-collectif.md
Linked to https://pulse.cio.gov/ for extra context. Thanks!
> Added link to Pulse homepage.

- _data/team.yml
> Removed LinkedIn profile for Mario

- _pages/en/our-team.html
- _pages/en/products.html
- _pages/en/what-we-do.html
- _pages/fr/produits.html
Minor text changes (such as capitalization) to match style guide decisions, to be consistent across communications/platforms.
> Style guide consistency

- _includes/cds/site-menu.html
Made active state checking look for either the page title or url to match to make it flexible with pagination.
#244
> Fix for issue #244

- _posts/en/2017-08-03-why-canada-needs-a-digital-service.md
- _posts/en/2017-08-24-picking-our-projects.md
- _posts/en/2017-09-29-discussing-digital-in-french.md
- _posts/en/2017-10-24-framing-a-design-problem.md
- _posts/en/2017-12-07-always-a-challenge.md
- _posts/en/2018-01-09-hiring-at-cds.md
- _posts/en/2018-01-16-challenging-our-assumption.md
- _posts/en/2018-01-29-getting-prototypes-out-the-door.md
- _posts/en/2018-02-15-a-conducting-user-research-with-NRCan.html
- _posts/en/2018-02-15-b-colocating-with-NRCan.md
- _posts/en/2018-03-09-CDS-gets-its-first-CEO.md
- _posts/en/2018-03-26-automated-testing-blog.html
- _posts/en/2018-04-09-recruiting-our-ceo.md
- _posts/en/2018-04-13-reschedule-a-citizenship-appointment.html
- _posts/en/2018-04-19-our-partnership-with-code-for-canada.md
- _posts/en/2018-04-24-coding-is-a-team-activity.md
- _posts/en/2018-04-25-retrospective-on-energuide-api.md
- _posts/en/2018-05-16-reducing-risk-through-continuous-deployment.md
- _posts/en/2018-06-12-setting-users-up for-success-with-content-design.html
- _posts/en/2018-06-14-lets-talk-user-experience.html
- _posts/en/2018-06-27-tools-to-do-good-work.md
- _posts/en/2018-07-10-the-security-in-digital-is-silent.md
- _posts/en/2018-07-20-discovery-phase-understanding-the-problem.md
- _posts/en/2018-07-26-service-design-thats-our-jam.md
- _posts/en/2018-07-31-showing-the-whole-iceberg.md
Making sure title/headings are consistently formatted across all CDS blog posts.
> Blog style consistency

- _pages/en/products.html
- _pages/fr/produits.html
PR to update product contact from Dan to myself.
> Updating VAC product contact

- _pages/en/work-with-us.html
- _pages/fr/travaillez-avec-nous.html
- Move open streams into blue box at the top of the page.
- Re-add Design and Comms streams
> Work with us layout changes per Andrea's request

- _posts/en/2018-08-31-rfp.md
- _posts/fr/2018-08-31-ddp.md
Reverts cds-snc/digital-canada-ca#328
I jumped the gun a bit
> Revert "rfp deadline change"

- _posts/en/2018-08-31-rfp.md
- _posts/fr/2018-08-31-ddp.md
Reverts cds-snc/digital-canada-ca#329
This is to revert the reverting we did earlier - aka the rfp update is actually okay'd to go live now.
> Revert "Revert "rfp deadline change""

- _pages/en/products.html
- _pages/fr/produits.html
> Move https and e-regs to past products 

- content/en/blog/posts/supporting-users-gracefully-degrading-react.md
- content/fr/blog/posts/supporter-utilisateurs-degradation-progressive-react.md
We're going to be 404-ing requests to the root domain for the rescheduler in about a month's time so just getting ahead of it.
> Update rescheduler domain in previous blog post

- layouts/section/story.html
Grids are the bane of my existence - fix smaller desktop views
> Fix sizing

- content/fr/products/products/aider-les-canadiens-à-faible-revenu-à-produire-leur-déclaration-fiscale.md
- layouts/products/list.html
Netlify CMS makes the list nil instead of an empty array
> Fix for nil product list variable

- content/en/products/products/report-a-cybercrime.md
- content/fr/products/products/aider-les-canadiens-à-faible-revenu-à-produire-leur-déclaration-fiscale.md
- content/fr/products/products/signaler-un-cybercrime.md
- static/admin/config.yml
And fixing new products that were affected
> Bad config value

- README.md
> README: Fixes a typo in the French port number

- config.yaml
- layouts/_default/list.html
This disables and removes taxonomy  the warnings.
> Fix taxonomy warnings

- README.md
Translation from TBS translation, checked with Élise. Also tweaked the English README a bit, full description in commits. Insubstantial changes to content, reflected in both EN/FR versions. 
Closes #182 🎉
> Traduire le README

- content/en/products/products/report-a-cybercrime.md
- content/fr/products/products/aider-les-canadiens-à-faible-revenu-à-produire-leur-déclaration-fiscale.md
- content/fr/products/products/signaler-un-cybercrime.md
Update on Products page: https://digital.canada.ca/products/
Under RCMP project entitled "Report a cybercrime," changed from Discovery to **Alpha**.
> Update to Products page: changed RCMP project from Discovery to Alpha

- package-lock.json
- package.json
- util/lib/getFileInfo.js
- util/processBlogImages.js
- Adds script read blog images from markdown files
- Creates a JPEG images (thumbnail image + "large" image)
- Updates markdown files to be able to use these images
- Adds a processed element to Front Matter so we can ensure this only happens one time.
===============================
I'll setup a second PR which will use the new params in the templates.
> PT 1 - Process blog images

- config/_default/config.yaml
- i18n/en.yaml
> Meet the team

- static/admin/config.yml
Adding hidden fields to Netlify config.
Given the image processing scripts adding these fields to ensure things stay in sync.  
Seems like for the team.yml the processed attribute keeps getting removed, also the thumbnails seem to disappear from time to time.
> Add netlify fields

- content/en/blog/posts/small-acts-big-impacts.md
- content/fr/blog/posts/de-petits-gestes-ayant-des-retombées-significatives.md
- fixed bullet points for ENG + FR version of blog post
- also addressed thumbnail image adding thumb field
> Fixed bullet points + thumbnail image for blog post "Small Acts, Big Impacts"

- content/en/blog/posts/what’s-it-like-to-work-on-a-distributed-team.md
Replaced the bold text and added links to:
- Slack
- Google hangouts
- Google Drive
- Trello
- Sketch
- Figma
> Added hyperlinks to the tools

- content/en/blog/posts/setting-users-up for-success-with-content-design.md
- content/fr/blog/posts/donner-aux-utilisateurs-les-moyens-de-réussir.md
pretty straightforward text change
> Changing the name on my blog post (EN)

- assets/sass/cds/_nav.scss
- i18n/en.yaml
- i18n/fr.yaml
- layouts/products/list.html
- layouts/section/platform.html
- layouts/section/products.html
Adds product toggle per the mock by @nmakuch 
Note: Button names etc... need translation.
> Add product toggle

- layouts/section/job-posting.en.html
- layouts/section/job-posting.fr.html
> Apply Form - Wording update

- assets/sass/cds/_sections.scss
Changed Discovery tags from EN to FR product page are in English for ESDC and PSPC
> Changed 'discovery' tags to french (Découverte) for products on french product page

- content/en/work-with-us/positions/policy-analyst.md
- content/fr/work-with-us/positions/analyste-des-politiques.md
Made changes to English + French job posting, "Policy Analyst":
1) English - "Policy Analyst (co-op)"
translationKey: d81198b9-3536-4a4d-a370-576b94ac7f2a
2) French - "Analyste des politiques (étudiant)"
translationKey: c085b289-749f-4a64-8c01-9973c4ba3293
> added student to job posting and changed translation key

- content/en/blog/posts/global-skills-strategy.md
- content/fr/blog/posts/strategie-en-matiere-de-competences-mondiales.md
> Fix broken image

- content/fr/stratosphere.html
Translation proofed and approved by Mario
> Updating with Translated French content

- content/en/cppd-research.html
- content/fr/cppd-research.html
> Swapping contact email for CPPD research page 

- content/fr/cppd-research.html
Making sure the FR matches the new changes in EN
> swapping contact and updating content FR

- content/en/cppd-research.html
- content/fr/cppd-research.html
Edit intro to CPP-D recruitment page to better match the new recruitment posters.
> Update CPP-D intro copy

- content/en/join-our-team/positions/senior-developers.md
- content/fr/join-our-team/positions/développeurs-expérimentés.md
**ENG:** 
Changed from "We're hiring people at all levels on experience in Ottawa, Toronto, Waterloo, and Montreal" to **"We're hiring in Ottawa, Toronto, Waterloo, and Montreal."**
**FR:** 
Changed from "Nous embauchons des personnes de tous les niveaux d’expérience, à Ottawa, Toronto, Waterloo et Montréal" to **"Nous embauchons à Ottawa, Toronto, Waterloo et Montréal."**
> Made change to Senior Dev job posting

- static/admin/config.yml
Super easy fix for the job posting API error as It's was not pointing to the correct directory.
> [DON'T MERGE] Added the correct Netlify path for job postings directory

- assets/sass/cds/_layout.scss
- content/en/tools-and-resources/evaluation-framework.html
- content/en/tools-and-resources/tools-and-resources/evaluation-framework.md
- content/fr/tools-and-resources/evaluation-framework.html
- content/fr/tools-and-resources/tools-and-resources/evaluation-framework.md
Added the following:
- English + French blurbs to Tools and Resources page linking to the below individual pages
- Individual English + French pages with documentation for CDS Product Evaluation Framework
> Product Evaluation Framework page (Tools and Resources)

- assets/sass/cds/_base.scss
- assets/sass/cds/_layout.scss
- assets/sass/cds/_nav.scss
- i18n/en.yaml
- i18n/fr.yaml
- layouts/index.html
- layouts/partials/footer-links.html
- layouts/partials/footer.html
- layouts/partials/menu.html
- static/img/cds/goc--footer-logo.svg
This Cl updates the header and footer to the new style.
> Update GOC header/footer.

- static/admin/config.yml
Based on the doc that we worked on previously to finalize all metadata fields and descriptions
> Form required/optional updates

- content/en/products/products/help-canadians-access-the-cpp-disability-benefit.md
- content/en/products/products/help-canadians-with-low-income-file-taxes.md
- content/en/products/products/make-it-easier-to-identify-tender-opportunities.md
- content/en/products/products/notify.md
- content/fr/products/products/aider-les-canadiennes-et-les-canadiens-à-recevoir-des-prestations-d’invalidité-du-rpc.md
- content/fr/products/products/aider-les-canadiens-à-faible-revenu-à-produire-leur-déclaration-fiscale.md
- content/fr/products/products/faciliter-le-repérage-d’appels-d’offres.md
- content/fr/products/products/notify.md
- layouts/index.html
This CL changes the products shown on the homepage from being random to begin a set list.
> Update products shown on homepage

- content/en/products/products/help-canadians-access-the-cpp-disability-benefit.md
- content/fr/products/products/aider-les-canadiennes-et-les-canadiens-à-recevoir-des-prestations-d’invalidité-du-rpc.md
> Adding URLs for CPPD doc 

- i18n/en.yaml
Added period at the end of Products blurb on Homepage:
https://trello.com/c/yOMp0Wae/75-fix-typo
> Fixed typo on Homepage - Products blurb

- assets/sass/cds/_base.scss
- assets/sass/cds/_layout.scss
- assets/sass/cds/_nav.scss
- assets/sass/cds/_sections.scss
- config/_default/config.yaml
- content/en/_index.html
- content/fr/_index.html
- layouts/_default/baseof.html
- layouts/index.html
- layouts/partials/menu.html
- layouts/section/join-our-team.en.html
- layouts/section/join-our-team.fr.html
- layouts/section/tools-and-resources.html
This PR incorporates homepage header styles from PR #1036 
Things to add:
- wordless logo on mobile view 
- additional padding
- change hamburger menu style
Trello card: https://trello.com/c/51mN5pqY/69-merging-new-cds-header-for-the-homepage
> Homepage Header styles (incorporating work from Dan's PR #1036)

- assets/sass/cds/_sections.scss
- i18n/en.yaml
- i18n/fr.yaml
- layouts/index.html
- layouts/section/partnerships.html
- fixed French "Partenaire" label on website
- add links to Partnerships page
> Partnership-related fixes (Homepage + Partnerships page)

- assets/sass/cds/_nav.scss
- layouts/partials/menu.html
This PR changes the existing hamburger menu to one resembling the design mockup. 
It also fixes the menu being greyed out on some pages.
https://trello.com/c/qMFmgAGS/82-replace-hamburger-menu-with-new-one-featured-in-mockup
> Ready 2 merge: Style changes + fixes to hamburger menu

- content/en/blog/posts/b-colocating-with-NRCan.md
- content/en/blog/posts/co-location-leave-no-team-member-behind.md
- content/en/blog/posts/community-driven-coding.md
- content/en/blog/posts/discovery-phase-understanding-the-problem.md
- content/en/blog/posts/lexicon.md
- content/en/blog/posts/productive-collaboration.md
- content/en/blog/posts/reducing-risk-through-continuous-deployment.md
- content/en/blog/posts/service-design-thats-our-jam.md
- content/en/blog/posts/supporting-users-gracefully-degrading-react.md
- content/fr/blog/posts/b-travailler-dans-les-locaux-de-RNCan.md
- content/fr/blog/posts/codage-collectif.md
- content/fr/blog/posts/collaboration-productive.md
- content/fr/blog/posts/colocalisation-ne-laisser-aucun-membre-de-l’équipe-derrière.md
- content/fr/blog/posts/la-phase-de-decouverte-comprendre-le-probleme.md
- content/fr/blog/posts/reduire-le-risque-grace-au-deploiement-continu.md
- content/fr/blog/posts/strategie-en-matiere-de-competences-mondiales.md
- content/fr/blog/posts/supporter-utilisateurs-degradation-progressive-react.md
Fixes a bunch of markdown errors, including the ones identified in #1024
> Fix a bunch of markdown errors

- assets/sass/cds/_base.scss
- assets/sass/cds/_components.scss
- assets/sass/cds/_sections.scss
- i18n/en.yaml
- i18n/fr.yaml
- layouts/index.html
- layouts/section/blog.html
New hover states for links and buttons on:
- Homepage
- Partnerships page
https://trello.com/c/YlJf5JJg/111-hover-states-for-links-and-buttons
> Ready to merge: Changed hover states for links and buttons

- assets/sass/cds/_sections.scss
- i18n/en.yaml
- i18n/fr.yaml
- layouts/index.html
This PR includes:
- Changes to homepage blurb from "Read all our blog posts" to "Read all blog posts" in EN + FR 
- Small design fixes aligning the arrow icon with "Read all blog posts" blurb
> Changed homepage blurb from "Read all our blog posts" to "Read all blog posts" in EN + FR

- assets/sass/cds/_sections.scss
- content/en/form-submission/error-stratosphere.md
- content/en/join-our-team/_index.html
- content/fr/join-our-team/_index.html
- layouts/section/job-posting.en.html
- layouts/section/join-our-team.en.html
- layouts/section/join-our-team.fr.html
This PR includes small fixes to the "Join our team" page, including: 
- Content 
- Hover states for links and buttons
- Some updated margin and padding styles
- Standardizing h3 styles
> Ready to merge: Fixing odds and ends for Join our team page + Application section

- content/en/rcmp-research.html
- content/fr/rcmp-research.html
- i18n/en.yaml
- i18n/fr.yaml
> Create recruitment webpage for RCMP research

- content/en/blog/posts/how-communications-and-data-can-live-happily-ever-after.md
- content/fr/blog/posts/communications-et-données-elles-vécurent-heureuses-jusqu’à-la-fin-des-temps.md
Fixes minor formatting glitches in the EN and FR Mailchimp posts.
> Minor text fixes.

- content/en/products/products/help-canadians-access-the-cpp-disability-benefit.md
- content/en/products/products/report-a-cybercrime.md
- content/fr/products/products/aider-les-canadiennes-et-les-canadiens-à-recevoir-des-prestations-d’invalidité-du-rpc.md
- content/fr/products/products/signaler-un-cybercrime.md
- ESDC to Alpha
- RCMP to Beta
> updates to product phases

- content/en/products/products/report-a-cybercrime.md
- content/fr/products/products/signaler-un-cybercrime.md
**English:**
Iterating on a service that makes it easier for victims of cybercrime to report an incident and get guidance on what they can do to protect themselves.
**French:**
Itération d'un service qui permet aux victimes de la cybercriminalité de signaler plus facilement un incident et d'obtenir des conseils sur ce qu'elles peuvent faire pour se protéger.
> updated RCMP product description

- content/en/products/products/help-canadians-access-the-cpp-disability-benefit.md
- content/fr/products/products/aider-les-canadiennes-et-les-canadiens-à-recevoir-des-prestations-d’invalidité-du-rpc.md
Adding the link to the repo for Help Canadians access the CPP Disability Benefit.
> Adding GitHub URL for CPPD 

- assets/sass/cds/_sections.scss
This PR fixes the title backgrounds (change back to black) and margins of all single blog pages.
> Fixed titles for single blog pages

- content/fr/blog/posts/le-problème-inattendu-de-l’infolettre-française.md
- content/fr/blog/posts/pourquoi-le-code-source-libre-est-il-important.md
- content/fr/blog/posts/pouvez-vous-encadrer-la-communauté-de-développeurs-logiciel-du-snc.md
-one edit to Jeff's blog on chief of development posting
-one edit to open source blog
> edits to french blog posts

- content/en/esdc-c19-research.html
- content/fr/esdc-c19-research.html
Urgent, to support ESDC C19 benefit clarifier work.
> ESDC-C19 recruitment page

- content/fr/esdc-c19-research.html
Also got rid of weird ticks in the text
> changed my email to Phil C's

- content/fr/esdc-c19-research.html
did a more careful read-through ...
> Apostrophes and changing all email addresses

- content/fr/tools-and-resources/platform-tools/a11y-tracker.md
- content/fr/tools-and-resources/platform-tools/bookings.md
- content/fr/tools-and-resources/platform-tools/continuous-security.md
- content/fr/tools-and-resources/platform-tools/forms.md
- i18n/fr.yaml
> edited fr tools and resources page

- content/en/notify-research.html
- content/en/rcmp-research.html
- content/en/tools-and-resources/platform-tools/forms.md
- content/fr/notify-research.html
- content/fr/rcmp-research.html
- content/fr/tools-and-resources/platform-tools/forms.md
- Update for RCMP research page
- Update for Forms product card contact link
> Website updates 

- assets/sass/cds/_layout.scss
- assets/sass/cds/_sections.scss
- content/en/_index.html
- content/fr/_index.html
- i18n/en.yaml
- i18n/fr.yaml
- layouts/_default/baseof.html
- layouts/a11y/default.html
- layouts/engagement/default.html
- layouts/partials/menu.html
- layouts/partials/social-links.html
- layouts/roadmap/baseof.html
Fixes for:
ARIA role must be appropriate for the element
Headings must not be empty
All page content must be contained by landmarks
Headers should only increase by one
Add missing translation
> A11y fixes

- content/en/covid-health-research.html
- content/fr/covid-health-research.html
Updating the EN and FR pages to make the text flexible for future activities.
> Covid health recruitment update

- content/en/join-our-team/positions/creative-recruiter.md
- content/en/products/products/exposure-notifications.md
- content/fr/join-our-team/positions/recruteur-créatif-recruteuse-créative.md
- content/fr/products/products/exposure-notifications.md
This PR includes the following general website updates:
- Link addition to EN product cards
- Updates to Creative Recruiter position
> Updates: Job postings + product cards

- content/en/exposure-notification-app-privacy-policy.html
- content/fr/exposure-notification-app-privacy-policy.html
This PR includes content updates to the English and French Exposure Notification app Privacy Pages.
> Updates to Exposure Notification app Privacy Pages 

- content/en/join-our-team/positions/senior-principal-software-developer.md
- content/fr/join-our-team/positions/développeur-de-logiciel-senior-principal-e.md
Close the position to new applicants.
> Take down Senior/Principal Dev Job Posting

- content/en/tools-and-resources/platform-tools/bookings.md
- content/en/tools-and-resources/platform-tools/forms.md
- content/fr/tools-and-resources/platform-tools/bookings.md
- content/fr/tools-and-resources/platform-tools/forms.md
> Updated descriptions and links for Platform product cards

- content/en/join-our-team/positions/partnerships-advisor.md
- content/fr/join-our-team/positions/conseiller-en-partenariats.md
> Content updates to Partnerships Advisor page

- content/fr/blog/posts/mesurer-l’impact-d’alerte-covid-grâce-aux-mesures-de-perf.md
> Fixed FR title for metrics blog

- content/en/blog/posts/gc-notify-has-reached-beta.md
- content/fr/blog/posts/gc-notification-maintenant-en-version-bêta.md
> Update to Notify Beta blog posts

- content/en/blog/posts/gc-notify-has-reached-beta.md
- content/fr/blog/posts/gc-notification-maintenant-en-version-bêta.md
> Updates to Notify Beta blog - text messages

- layouts/section/meet-the-team.html
Meet the team page - titles were only displaying in english
> Fix titles being english only

- data/team.yml
> [AUTO-PR] New content release -  2021-02-22T17:55:14.419Z

- data/team.yml
> [AUTO-PR] New content release -  2021-02-22T18:39:00.981Z

- package-lock.json
- package.json
- webpack.config.js
This PR addresses all the various Snyk PRs that have been laying around, as just generally upgrading dependencies. Webpack configuration slightly changed as part of the migration from 4 to 5.
> Upgrade dependencies

- content/en/products/products/government-of-canada-exposure-notifications-mobile-app.md
- content/en/tools-and-resources/platform-tools/help-public-servants-create-and-manage-forms.md
- content/en/tools-and-resources/resources/accessibility-handbook.md
- content/fr/products/products/application-mobile-de-notification-d’exposition-du-gouvernement-du-canada.md
- content/fr/tools-and-resources/platform-tools/aider-les-fonctionnaires-à-créer-et-à-gérer-des-formulaires.md
- content/fr/tools-and-resources/resources/le-guide-d’accessibilité.md
> [AUTO-PR] New content release -  2021-03-01T21:33:49.125Z

- assets/sass/cds/_sections.scss
- layouts/products/list.html
- layouts/tools-and-resources/list.html
> Adding classes to Product links for Google Tag Manager

- content/en/products/products/e-briefing-app.md
- content/en/products/products/energuide-api.md
- content/en/products/products/find-financial-help-during-covid-19.md
- content/en/products/products/find-relevant-benefits-for-veterans.md
- content/en/products/products/guidance-on-regulatory-consultation.md
- content/en/products/products/help-canadians-access-the-cpp-disability-benefit.md
- content/en/products/products/help-canadians-with-low-income-file-taxes.md
- content/en/products/products/impact-canada-challenge-platform.md
- content/en/products/products/make-it-easier-to-identify-tender-opportunities.md
- content/en/products/products/open-call-catalogue-to-help-governments-respond-to-covid-19.md
- content/en/products/products/report-a-cybercrime.md
- content/en/products/products/reschedule-a-citizenship-test.md
- content/en/products/products/track-web-security-compliance.md
- content/fr/products/products/aider-les-canadiennes-et-les-canadiens-à-recevoir-des-prestations-d’invalidité-du-rpc.md
- content/fr/products/products/aider-les-canadiens-à-faible-revenu-à-produire-leur-déclaration-fiscale.md
- content/fr/products/products/api-énerguide.md
- content/fr/products/products/application-de-breffage-électronique.md
- content/fr/products/products/faciliter-le-repérage-d’appels-d’offres.md
- content/fr/products/products/faire-des-recommandations-en-vue-des-consultations-sur-la-réglementation.md
- content/fr/products/products/le-catalogue-appel-ouvert-pour-aider-les-gouvernements-à-répondre-à-la-crise-de-la-covid-19.md
- content/fr/products/products/plateforme-de-défis-impact-canada.md
- content/fr/products/products/reporter-un-examen-de-citoyenneté.md
- content/fr/products/products/signaler-un-crime-informatique.md
- content/fr/products/products/suivre-ou-vérifier-la-confirmité-en-matière-de-sécurité-web.md
- content/fr/products/products/trouver-de-l’aide-financière-pendant-la-pandémie-de-covid-19.md
- content/fr/products/products/trouver-les-prestations-pertinentes-pour-les-vétérans.md
> [AUTO-PR] New content release -  2021-03-03T18:06:54.426Z

- content/en/tools-and-resources/resources/a-guide-to-research-interviewing.md
- content/en/tools-and-resources/resources/a-guide-to-usability-testing.md
- content/en/tools-and-resources/resources/cds-product-evaluation-framework.md
- content/en/tools-and-resources/resources/digital-government-reading-list.md
- content/fr/tools-and-resources/resources/cadre-d’évaluation-des-produits-du-snc.md
- content/fr/tools-and-resources/resources/liste-de-lecture-sur-le-gouvernement-numérique.md
- content/fr/tools-and-resources/resources/un-guide-pour-les-entrevues-de-recherche.md
- content/fr/tools-and-resources/resources/un-guide-pour-les-tests-d’utilisabilité.md
> [AUTO-PR] New content release -  2021-03-03T20:27:55.365Z

- content/en/tools-and-resources/platform-tools/help-public-servants-create-and-manage-forms.md
- content/fr/tools-and-resources/platform-tools/aider-les-fonctionnaires-à-créer-et-à-gérer-des-formulaires.md
> [AUTO-PR] New content release -  2021-03-12T15:55:58.608Z

- content/en/blog/posts/learning-to-make-twitter-content-more-accessible.md
- content/fr/blog/posts/-apprendre-à-rendre-le-contenu-sur-twitter-plus-accessible.md
> [AUTO-PR] New content release -  2021-03-12T16:58:50.564Z

- content/en/blog/posts/learning-to-make-twitter-content-more-accessible.md
- content/fr/blog/posts/-apprendre-à-rendre-le-contenu-sur-twitter-plus-accessible.md
- data/team.yml
> [AUTO-PR] New content release -  2021-03-12T19:45:22.359Z

- content/en/join-our-team/positions/full-stack-developer-partnerships.md
- content/en/join-our-team/positions/full-stack-software-developer-platform.md
- content/fr/join-our-team/positions/développeur-généraliste-partenariats.md
> [AUTO-PR] New content release -  2021-03-15T13:43:38.667Z

- content/en/blog/posts/learning-to-make-twitter-content-more-accessible.md
- content/fr/blog/posts/-apprendre-à-rendre-le-contenu-sur-twitter-plus-accessible.md
> [AUTO-PR] New content release -  2021-03-15T13:50:35.769Z

- content/fr/join-our-team/positions/développeur-généraliste-plateforme.md
> [AUTO-PR] New content release -  2021-03-15T13:57:53.989Z

- content/en/blog/posts/learning-to-make-twitter-content-more-accessible.md
- content/fr/blog/posts/-apprendre-à-rendre-le-contenu-sur-twitter-plus-accessible.md
> [AUTO-PR] New content release -  2021-03-15T14:13:37.498Z

- content/en/join-our-team/positions/internal-communications-advisor.md
- content/fr/join-our-team/positions/conseiller-conseillère-en-communications-internes.md
> [AUTO-PR] New content release -  2021-03-15T14:28:22.124Z

- .github/workflows/a11y_tracking.yaml
The PR fixes the CI scan by using valid json 🤞
> fix: use valid json

- content/en/blog/posts/learning-to-make-twitter-content-more-accessible.md
- content/en/blog/posts/reflecting-on-what-i-learned-from-working-on-design-research-operations.md
- content/fr/blog/posts/-apprendre-à-rendre-le-contenu-sur-twitter-plus-accessible.md
> [AUTO-PR] New content release -  2021-03-15T20:25:16.893Z

- content/en/join-our-team/positions/senior-agile-delivery-manager-covid-alert.md
- content/fr/join-our-team/positions/gestionnaire-de-livraison-agile-sénior-alerte-covid.md
> [AUTO-PR] New content release -  2021-03-18T13:40:23.735Z

- content/en/blog/posts/busting-talent-myths-to-hire-multidisciplinary-teams.md
- content/en/blog/posts/learning-to-make-twitter-content-more-accessible.md
- content/en/blog/posts/reflecting-on-what-i-learned-from-working-on-design-research-operations.md
- content/fr/blog/posts/-apprendre-à-rendre-le-contenu-sur-twitter-plus-accessible.md
- content/fr/blog/posts/démystifier-les-mythes-des-équipes-de-talents-pour-embaucher-des-équipes-multidisciplinaires.md
> [AUTO-PR] New content release -  2021-03-18T15:12:54.114Z

- data/team.yml
> [AUTO-PR] New content release -  2021-03-18T18:12:28.773Z

- content/fr/join-our-team/positions/gestionnaire-de-livraison-agile-sénior-alerte-covid.md
- data/team.yml
> [AUTO-PR] New content release -  2021-03-22T13:09:32.819Z

- content/fr/join-our-team/positions/gestionnaire-de-livraison-agile-sénior-alerte-covid.md
> [AUTO-PR] New content release -  2021-03-23T15:58:16.140Z

- data/team.yml
> [AUTO-PR] New content release -  2021-03-24T16:57:09.987Z

- content/en/blog/posts/testing-assumptions-before-fixing-problems.md
- content/fr/blog/posts/tester-ses-hypothèses-avant-de-résoudre-des-problèmes.md
> [AUTO-PR] New content release -  2021-03-25T15:49:01.946Z

- content/en/blog/posts/testing-assumptions-before-fixing-problems.md
- content/fr/blog/posts/tester-ses-hypothèses-avant-de-résoudre-des-problèmes.md
> [AUTO-PR] New content release -  2021-03-25T16:16:29.421Z

- content/en/join-our-team/positions/covid-alert-sre-developer.md
- content/fr/join-our-team/positions/développeur-de-l’ifs-sre-d’alerte-covid.md
- data/team.yml
> [AUTO-PR] New content release -  2021-03-26T13:23:53.347Z

- content/en/tools-and-resources/platform-tools/help-public-servants-create-and-manage-forms.md
- content/fr/tools-and-resources/platform-tools/aider-les-fonctionnaires-à-créer-et-à-gérer-des-formulaires.md
> [AUTO-PR] New content release -  2021-03-26T19:30:39.821Z

- data/team.yml
> [AUTO-PR] New content release -  2021-03-30T19:46:01.600Z

- content/fr/join-our-team/positions/développeur-de-soutien.md
> [AUTO-PR] New content release -  2021-04-01T17:57:44.198Z

- content/en/join-our-team/positions/policy-advisor.md
- content/en/join-our-team/positions/senior-policy-advisor.md
- content/fr/join-our-team/positions/conseiller-ère-en-politiques.md
- content/fr/join-our-team/positions/conseiller-ère-principal-e-en-politiques.md
> [AUTO-PR] New content release -  2021-04-01T20:26:47.895Z

- content/en/join-our-team/positions/senior-principal-software-developer-python.md
- content/fr/join-our-team/positions/développeur-de-logiciel-senior-principal-e-python.md
> [AUTO-PR] New content release -  2021-04-06T15:40:25.546Z

- content/en/blog/posts/exploring-the-conditions-for-digital-service-delivery.md
- content/fr/blog/posts/explorer-les-conditions-de-la-prestation-de-services-numériques.md
> [AUTO-PR] New content release -  2021-04-07T13:53:53.211Z

- content/en/join-our-team/positions/platform-sre-developer.md
- content/fr/join-our-team/positions/développeur-de-l’ifs-sre-de-plateformes.md
> [AUTO-PR] New content release -  2021-04-07T16:53:46.768Z

- content/en/join-our-team/positions/technical-support-developer.md
- content/fr/join-our-team/positions/développeur-de-soutien.md
> [AUTO-PR] New content release -  2021-04-08T20:59:52.412Z

- content/en/join-our-team/positions/senior-agile-delivery-manager-partnerships.md
- content/fr/join-our-team/positions/gestionnaire-principal-de-la-livraison-agile-partenariats.md
> [AUTO-PR] New content release -  2021-04-09T19:02:05.463Z

- content/en/join-our-team/positions/senior-agile-delivery-manager-partnerships.md
- content/fr/join-our-team/positions/gestionnaire-principal-de-la-livraison-agile-partenariats.md
> [AUTO-PR] New content release -  2021-04-09T19:20:16.055Z

- content/en/join-our-team/positions/policy-advisor.md
- content/fr/join-our-team/positions/conseiller-ère-en-politiques.md
> [AUTO-PR] New content release -  2021-04-09T20:11:24.736Z

- content/en/join-our-team/positions/senior-product-manager---partnerships.md
- content/fr/join-our-team/positions/gestionnaire-principal-de-produit-–-partenariats.md
> [AUTO-PR] New content release -  2021-04-13T13:33:40.918Z

- content/en/join-our-team/positions/senior-front-end-software-developer.md
- content/fr/join-our-team/positions/développeur-principal-de-logiciels-frontaux.md
> [AUTO-PR] New content release -  2021-04-16T18:30:37.238Z

- content/en/join-our-team/positions/policy-delivery-team-lead.md
- content/fr/join-our-team/positions/chef-de-l’équipe-d’exécution-des-politiques.md
> [AUTO-PR] New content release -  2021-04-20T19:27:42.470Z

- content/en/join-our-team/positions/executive-assistant.md
- content/fr/join-our-team/positions/adjoint-e-de-direction.md
> [AUTO-PR] New content release -  2021-04-20T20:33:30.070Z

- content/en/join-our-team/positions/executive-assistant.md
- content/fr/join-our-team/positions/adjoint-e-de-direction.md
> [AUTO-PR] New content release -  2021-04-20T21:46:17.452Z

- content/en/join-our-team/positions/senior-or-principal-content-designer.md
- content/en/join-our-team/positions/senior-service-designer.md
- content/fr/join-our-team/positions/concepteur-de-contenu-principal-ou-conceptrice-de-contenu-principale.md
- content/fr/join-our-team/positions/concepteur-principal-ou-conceptrice-principale-de-service.md
> [AUTO-PR] New content release -  2021-04-26T14:20:22.063Z

- content/en/join-our-team/positions/senior-or-principal-content-designer.md
- content/en/join-our-team/positions/senior-service-designer.md
- content/fr/join-our-team/positions/concepteur-de-contenu-principal-ou-conceptrice-de-contenu-principale.md
- content/fr/join-our-team/positions/concepteur-principal-ou-conceptrice-principale-de-service.md
> [AUTO-PR] New content release -  2021-04-26T15:51:47.026Z

- content/en/join-our-team/positions/senior-or-principal-content-designer.md
- content/en/join-our-team/positions/senior-service-designer.md
- content/fr/join-our-team/positions/concepteur-de-contenu-principal-ou-conceptrice-de-contenu-principale.md
- content/fr/join-our-team/positions/concepteur-principal-ou-conceptrice-principale-de-service.md
> [AUTO-PR] New content release -  2021-04-26T17:08:45.088Z

- content/en/join-our-team/positions/senior-or-principal-content-designer.md
- content/en/join-our-team/positions/senior-service-designer.md
- content/fr/join-our-team/positions/concepteur-de-contenu-principal-ou-conceptrice-de-contenu-principale.md
- content/fr/join-our-team/positions/concepteur-principal-ou-conceptrice-principale-de-service.md
> [AUTO-PR] New content release -  2021-04-26T17:19:19.287Z

- content/en/join-our-team/positions/policy-delivery-team-lead.md
- content/en/join-our-team/positions/senior-policy-advisor.md
- content/fr/join-our-team/positions/chef-de-l’équipe-d’exécution-des-politiques.md
- content/fr/join-our-team/positions/conseiller-ère-principal-e-en-politiques.md
> [AUTO-PR] New content release -  2021-04-26T21:15:31.694Z

- content/en/join-our-team/positions/senior-service-designer.md
- content/fr/join-our-team/positions/concepteur-principal-ou-conceptrice-principale-de-service.md
> [AUTO-PR] New content release -  2021-04-29T21:33:26.833Z

- content/en/tools-and-resources/platform-tools/help-public-servants-create-and-manage-forms.md
- content/fr/tools-and-resources/platform-tools/aider-les-fonctionnaires-à-créer-et-à-gérer-des-formulaires.md
> [AUTO-PR] New content release -  2021-05-03T14:38:46.757Z

- content/en/tools-and-resources/platform-tools/notify.md
- content/fr/tools-and-resources/platform-tools/notification.md
> Updating Notify product card

- content/en/join-our-team/positions/full-stack-developer-partnerships.md
- content/en/join-our-team/positions/full-stack-software-developer-platform.md
- content/en/join-our-team/positions/senior-product-manager---partnerships.md
- content/fr/join-our-team/positions/développeur-généraliste-partenariats.md
- content/fr/join-our-team/positions/développeur-généraliste-plateforme.md
- content/fr/join-our-team/positions/gestionnaire-principal-de-produit-–-partenariats.md
> [AUTO-PR] New content release -  2021-05-14T18:37:52.917Z

- content/en/blog/posts/busting-talent-myths-to-hire-multidisciplinary-teams.md
- content/en/join-our-team/positions/senior-agile-delivery-manager-partnerships.md
- content/fr/join-our-team/positions/gestionnaire-principal-de-la-livraison-agile-partenariats.md
> [AUTO-PR] New content release -  2021-05-18T19:16:58.798Z

- content/en/blog/posts/the-value-of-a-pause:-stories-of-change-in-the-rcmp.md
- content/fr/blog/posts/la-valeur-d’une-pause-:-histoires-de-changement-à-la-grc.md
> [AUTO-PR] New content release -  2021-05-19T14:13:59.655Z

- content/en/blog/posts/the-value-of-a-pause:-stories-of-change-in-the-rcmp.md
- content/fr/blog/posts/la-valeur-d’une-pause-:-histoires-de-changement-à-la-grc.md
> [AUTO-PR] New content release -  2021-05-19T14:36:22.914Z

- README.md
We're running off an old version of Hugo but don't specify this in our readme, despite newer versions causing breaking changes.
I've update the readme to reflect the version we use, instructions for installation, and a call out for help upgrading, linking to the relevant issue.
---
Make sure the language is clear, and the links are helpful and make sense.
---
> Y a-t-il des questions connexes que vous considérez hors sujet et qui
> pourraient être abordées plus tard?
This is a suggested checklist of questions reviewers might ask during their
review | Voici une suggestion de liste de vérification comprenant des questions
que les réviseurs pourraient poser pendant leur examen :
langues officielles?
une baisse de la quantité de code couvert par les tests automatisés?
fonctionnalité …
> Update readme to include info about Hugo version

- data/team.yml
> [AUTO-PR] New content release -  2021-05-27T21:09:07.320Z

- content/en/join-our-team/positions/senior-product-manager---partnerships.md
> [AUTO-PR] New content release -  2021-05-31T12:50:22.893Z

- content/fr/join-our-team/positions/gestionnaire-principal-de-produit-–-partenariats.md
> [AUTO-PR] New content release -  2021-05-31T12:54:57.090Z

- content/en/join-our-team/positions/policy-delivery-team-lead.md
- content/fr/join-our-team/positions/chef-de-l’équipe-d’exécution-des-politiques.md
> [AUTO-PR] New content release -  2021-06-01T16:52:03.013Z

- assets/sass/cds/_base.scss
- layouts/_default/baseof.html
- layouts/a11y/default.html
also force the font face mixin to use ttf
Fixing the name and extension of the font files 🤦‍♀️
And making sure the font face mixin knows it's ttf extension
This is a suggested checklist of questions reviewers might ask during their
review | Voici une suggestion de liste de vérification comprenant des questions
que les réviseurs pourraient poser pendant leur examen :
langues officielles?
une baisse de la quantité de code couvert par les tests automatisés?
fonctionnalité existante?
que ça devrait être divisé en de plus petites demandes de tirage (« pull
requests ») afin de réduire le risque lié aux modifications?
modification de la politique de confidentialité?
préoccupations liées à la sécurité?
façon importante la performance?
risque d’utiliser des dépendances ajoutées?
setup, etc.) | …
> fix the font file extension and name

- content/en/join-our-team/positions/covid-alert-sre-developer.md
- content/en/join-our-team/positions/platform-sre-developer.md
- content/fr/join-our-team/positions/développeur-de-l’ifs-sre-de-plateformes.md
> [AUTO-PR] New content release -  2021-06-02T19:09:04.818Z

- content/en/join-our-team/positions/covid-alert-sre-developer.md
> [AUTO-PR] New content release -  2021-06-02T19:22:51.527Z

- content/en/join-our-team/positions/executive-assistant.md
> [AUTO-PR] New content release -  2021-06-03T10:47:59.892Z

- content/en/our-values.html
- content/fr/our-values.html
- layouts/section/page-with-newsletter.html
This PR adds an our-values page. It is not linked from anywhere at this
point. The gray boxes in the mockup are missing, but the subscribe link
is provided for the newsletter.
Issue #2123
> Add Our Values page.

- content/en/join-our-team/positions/senior-service-designer.md
- content/fr/join-our-team/positions/concepteur-principal-ou-conceptrice-principale-de-service.md
> [AUTO-PR] New content release -  2021-06-07T13:51:25.516Z

- content/en/join-our-team/positions/executive-assistant.md
- content/fr/join-our-team/positions/adjoint-e-de-direction.md
> [AUTO-PR] New content release -  2021-06-07T17:42:46.268Z

- data/team.yml
> [AUTO-PR] New content release -  2021-06-08T18:17:28.476Z

- content/en/blog/posts/how-we’re-trying-to-make-virtual-onboarding-better.md
- content/fr/blog/posts/améliorer-l’intégration-des-nouveaux-employés-en-période-de-télétravail.md
> [AUTO-PR] New content release -  2021-06-09T14:42:23.511Z

- content/en/products/products/report-a-cybercrime.md
- content/fr/products/products/signaler-un-crime-informatique.md
Updated contact information / email link for the RCMP "Report a cybercrime" partnership (also updated to display on homepage in both English and French).
---
> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.
> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.
---
> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure …
> Updated contact email for the "Report a cybercrime" partnership

- content/en/join-our-team/positions/translator-content-coordinator.md
- content/fr/join-our-team/positions/traducteur-traductrice---coordonateur-coordonatrice-de-contenu.md
> [AUTO-PR] New content release -  2021-06-18T19:54:45.091Z

- content/en/join-our-team/positions/translator-content-coordinator.md
- content/fr/join-our-team/positions/traducteur-traductrice---coordonateur-coordonatrice-de-contenu.md
> [AUTO-PR] New content release -  2021-06-21T13:47:57.935Z

- content/fr/join-our-team/positions/traducteur-traductrice---coordonateur-coordonatrice-de-contenu.md
> [AUTO-PR] New content release -  2021-06-21T13:59:27.687Z

- content/en/tools-and-resources/platform-tools/help-public-servants-create-and-manage-forms.md
- content/fr/tools-and-resources/platform-tools/aider-les-fonctionnaires-à-créer-et-à-gérer-des-formulaires.md
> [AUTO-PR] New content release -  2021-06-23T15:13:47.101Z

- i18n/en.yaml
- i18n/fr.yaml
> Update Partnerships contact links temporarily

- content/en/tools-and-resources/platform-tools/help-public-servants-create-and-manage-forms.md
- content/fr/tools-and-resources/platform-tools/aider-les-fonctionnaires-à-créer-et-à-gérer-des-formulaires.md
> [AUTO-PR] New content release -  2021-06-25T13:37:59.365Z

- i18n/en.yaml
- i18n/fr.yaml
- layouts/partials/mailing-list.html
> Added link to Newsletter banner for past french newsletters

- content/en/blog/posts/a-faster-way-to-create-privacy-and-consent-notices-in-government.md
- content/fr/blog/posts/des-avis-de-confidentialité-et-de-consentement-en-un-clin-d’œil.md
> [AUTO-PR] New content release -  2021-06-30T14:26:57.371Z

- data/team.yml
> [AUTO-PR] New content release -  2021-07-06T15:02:40.478Z

- content/en/blog/posts/little-and-often:-making-critique-a-daily-practice.md
- content/fr/blog/posts/courtes-et-fréquentes-:-faire-de-la-critique-une-pratique-quotidienne.md
> [AUTO-PR] New content release -  2021-07-08T14:15:59.695Z

- content/fr/join-our-team/positions/traducteur-traductrice---coordonnateur-coordonnatrice-de-contenu.md
> [AUTO-PR] New content release -  2021-07-09T16:53:37.560Z

- config/_default/config.yaml
> Replacing "Home" with "Accueil" in French main menu

- content/en/join-our-team/positions/senior-or-principal-content-designer.md
- content/fr/join-our-team/positions/concepteur-de-contenu-principal-ou-conceptrice-de-contenu-principale.md
> Archive Sr Content Designer posting

- data/team.yml
> [AUTO-PR] New content release -  2021-07-16T13:49:50.443Z

- content/en/join-our-team/positions/senior-product-manager---platform.md
- content/fr/join-our-team/positions/gestionnaire-principal-e-de-produit---plateformes.md
> [AUTO-PR] New content release -  2021-07-16T14:54:27.552Z

- data/team.yml
> [AUTO-PR] New content release -  2021-07-22T17:24:37.109Z

- assets/sass/cds/_components.scss
- assets/sass/cds/_cta.scss
- assets/sass/cds/_layout.scss
- assets/sass/cds/_sections.scss
- content/en/meet-the-team.html
- content/en/our-values.html
- content/fr/meet-the-team.html
- content/fr/our-values.html
- i18n/en.yaml
- i18n/fr.yaml
- layouts/_default/baseof.html
This PR adds the missing titles from the Our Values and Meet the Team
pages.
Fixes #2420
> Add missing page titles.

- content/fr/blog/posts/tester-ses-hypothèses-avant-de-résoudre-des-problèmes.md
This PR matches the French heading levels to the English levels in the
`Testing assumptions before fixing problems` posting.
> Fix blog post heading levels.

- content/fr/blog/posts/tester-ses-hypothèses-avant-de-résoudre-des-problèmes.md
> [AUTO-PR] New content release -  2021-07-22T20:56:47.754Z

- assets/sass/cds/_sections.scss
- layouts/index.html
- layouts/products/list.html
- layouts/section/partnerships.html
- layouts/section/products.html
- layouts/section/tools-and-resources.html
- layouts/tools-and-resources/list.html
This PR sets the header level for the product cards based on a provided
level variable.
Fixes #2288
> Dynamically set header level.

- assets/sass/cds/_sections.scss
Formatting error caused some css issues.
from:
Fixed to:
> fixed css issue

- content/en/join-our-team/positions/senior-product-manager---platform.md
- content/fr/join-our-team/positions/gestionnaire-principal-e-de-produit---plateformes.md
> [AUTO-PR] New content release -  2021-07-26T17:11:48.411Z

- assets/sass/cds/_components.scss
- assets/sass/cds/_cta.scss
- assets/sass/cds/_sections.scss
> formatting

- content/en/blog/posts/using-data-to-meet-people’s-information-needs-during-the-pandemic.md
- content/fr/blog/posts/utiliser-les-données-pour-répondre-aux-besoins-d’information-pendant-la-pandémie.md
> [AUTO-PR] New content release -  2021-07-28T15:39:34.575Z

- data/team.yml
> [AUTO-PR] New content release -  2021-07-29T13:15:07.693Z

- content/en/website-usability-testing.html
- content/fr/website-usability-testing.html
The website team is conducting usability testing to understand the main challenges users experience when navigating certain webpages.
This PR includes an English and French draft for a Call for Research Participants page we will share on social media and GCconnex.
> Call for Research Participants page

- content/en/join-our-team/positions/senior-product-manager---platform.md
- content/fr/join-our-team/positions/gestionnaire-principal-e-de-produit---plateformes.md
> [AUTO-PR] New content release -  2021-08-10T12:33:45.820Z

- content/en/join-our-team/positions/senior-front-end-software-developer.md
- content/fr/join-our-team/positions/développeur-principal-de-logiciels-frontaux.md
> [AUTO-PR] New content release -  2021-08-12T20:19:39.166Z

- content/en/careers/positions/executive-assistant.md
- content/en/careers/positions/senior-front-end-software-developer.md
- content/en/careers/positions/technical-support-developer.md
- content/en/careers/positions/translator-content-coordinator.md
- content/fr/careers/positions/adjoint-e-de-direction.md
- content/fr/careers/positions/développeur-de-soutien.md
- content/fr/careers/positions/développeur-principal-de-logiciels-frontaux.md
- content/fr/careers/positions/traducteur-traductrice---coordonnateur-coordonnatrice-de-contenu.md
- paths.js
An update to some of the MD files. Since the URL for the job postings was changed, it is possible that there will be some users who will click on a broken link. To avoid that, I added a redirect to make sure it takes them to the correct page.
> Adding aliases to the existing job postings.

- content/en/careers/positions/technical-support-developer.md
- content/fr/careers/positions/développeur-de-soutien.md
> [AUTO-PR] New content release -  2021-08-17T15:23:16.978Z

- data/team.yml
> [AUTO-PR] New content release -  2021-08-19T20:46:30.913Z

- static/join-our-team/positions/développeur-de-soutien/index.html
- static/join-our-team/positions/développeur-principal-de-logiciels-frontaux/index.html
This PR updates the meta redirects to have URL encodings for the unicode
characters.
> Add URL encoding to redirect files.

- data/team.yml
> [AUTO-PR] New content release -  2021-08-24T15:08:28.585Z

- data/team.yml
> [AUTO-PR] New content release -  2021-09-01T20:29:53.702Z

- layouts/section/job-posting.en.html
- layouts/section/job-posting.fr.html
The open Github issue is regarding archived job postings. Even the posting is no longer accepting applicants, the apply now section was still open. This has been fixed by adding a conditional that does not display the "Apply now" link or the Apply now section. Only the job description and Asset Accommodation is available.
Link for archived posting: https://digital-cana-chore-hide-pzxr78.herokuapp.com/careers/positions/policy-analyst/
> conditional for apply now section

- content/en/careers/positions/full-stack-software-developer.md
- content/fr/careers/positions/développeur-ou-développeuse-généraliste.md
> [AUTO-PR] New content release -  2021-09-08T13:29:29.207Z

- content/en/careers/positions/full-stack-software-developer.md
- content/en/careers/positions/technical-support-developer.md
- content/fr/careers/positions/développeur-de-soutien.md
- content/fr/careers/positions/développeur-ou-développeuse-généraliste.md
> [AUTO-PR] New content release -  2021-09-08T15:15:00.578Z

- content/en/careers/positions/full-stack-software-developer.md
- content/fr/careers/positions/développeur-ou-développeuse-généraliste.md
> [AUTO-PR] New content release -  2021-09-08T16:57:35.753Z

- assets/sass/cds/_components.scss
- assets/sass/cds/_sections.scss
- assets/sass/engagement/_content.scss
- assets/sass/engagement/_headers.scss
- assets/sass/engagement/_nav.scss
- assets/sass/engagement/_print.scss
- assets/sass/engagement/_roadmap.scss
- assets/sass/engagement/_summary-page.scss
- content/en/spa-research.html
- content/fr/spa-research.html
Regarding issue: https://github.com/cds-snc/digital-canada-ca/issues/2230
Our base font size is 62.5% (or 1rem/10px).
I changed the px for `font-size` to rem
Changing from pixel to relative units such as rem will be better for scaling
> changed font size from px to rem

- content/en/careers/positions/full-stack-software-developer.md
- content/fr/careers/positions/développeur-ou-développeuse-généraliste.md
> [AUTO-PR] New content release -  2021-09-08T19:52:56.792Z

- content/en/careers/positions/full-stack-software-developer-mvp.md
- content/fr/careers/positions/développeur-ou-développeuse-généraliste-mvp.md
> [AUTO-PR] New content release -  2021-09-09T16:11:26.371Z

- content/en/careers/positions/technical-marketer.md
- content/fr/careers/positions/spécialiste-en-marketing-technique.md
> [AUTO-PR] New content release -  2021-09-10T14:37:43.284Z

- data/team.yml
> [AUTO-PR] New content release -  2021-09-13T12:30:36.026Z

- data/team.yml
> [AUTO-PR] New content release -  2021-09-13T17:39:38.860Z

- data/team.yml
> [AUTO-PR] New content release -  2021-09-16T19:18:19.488Z

- content/en/careers/positions/administrative-officer---internal-operations.md
- content/fr/careers/positions/agente-administrative-agent-administratif-–-opérations-internes.md
> [AUTO-PR] New content release -  2021-09-22T19:56:50.832Z

- data/team.yml
> [AUTO-PR] New content release -  2021-09-23T17:23:14.950Z

- data/team.yml
> [AUTO-PR] New content release -  2021-09-23T17:45:27.834Z

- data/team.yml
> [AUTO-PR] New content release -  2021-11-03T12:20:40.255Z

- layouts/partials/menu.html
- layouts/partials/search-list.html
- static/js/i18next.js
- static/js/lunr.js
Added source files for lunr and i18next to fix CSP issues
> added source files

- content/en/careers/positions/administrative-officer---internal-operations.md
- content/fr/careers/positions/agente-administrative-agent-administratif-–-opérations-internes.md
> [AUTO-PR] New content release -  2021-11-04T13:32:33.138Z

- content/en/careers/positions/team-lead-partnerships-business-development.md
- content/fr/careers/positions/responsable-d’équipe-développement-commercial-des-partenariats.md
> [AUTO-PR] New content release -  2021-11-05T14:56:54.709Z

- data/team.yml
> [AUTO-PR] New content release -  2021-11-09T17:32:49.907Z

- content/en/form-submission/error.md
- content/en/form-submission/success.md
- content/fr/form-submission/erreur.md
- content/fr/form-submission/reussi.md
Previously had "Success" and "Error" type on the MD file as "form-submission". Reverted back to "Section"
> fixed form submission issue

- content/en/careers/positions/executive-assistant.md
- content/fr/careers/positions/adjoint·e-exécutif·ve.md
> [AUTO-PR] New content release -  2021-11-10T19:14:29.061Z

- content/en/careers/positions/executive-assistant.md
- content/en/careers/positions/people-&-culture-coordinator.md
- content/en/careers/positions/people-operations-coordinator.md
- content/en/careers/positions/recruitment-administrator.md
- content/fr/careers/positions/administrateur-de-recrutement-administratrice-de-recrutement.md
- content/fr/careers/positions/coordonnateur-coordonnatrice-des-opérations-du-personnel.md
- content/fr/careers/positions/coordonnateur-coordonnatrice-du-personnel-et-de-la-culture.md
> [AUTO-PR] New content release -  2021-11-14T18:08:15.176Z

- content/en/careers/positions/executive-assistant.md
- data/team.yml
> [AUTO-PR] New content release -  2021-11-15T17:00:11.151Z

- content/en/careers/positions/executive-assistant.md
- data/team.yml
> [AUTO-PR] New content release -  2021-11-17T13:04:07.046Z

- content/en/careers/positions/executive-assistant---chief-operating-officer.md
- content/fr/careers/positions/adjoint·e-exécutif·ve---directeur-des-opérations.md
> [AUTO-PR] New content release -  2021-11-17T19:02:36.743Z

- content/en/careers/positions/executive-assistant---chief-operating-officer.md
- content/fr/careers/positions/adjoint·e-exécutif·ve---directeur-des-opérations.md
> [AUTO-PR] New content release -  2021-11-17T19:20:26.644Z

- content/en/tools-and-resources/platform-tools/notify.md
- content/fr/tools-and-resources/platform-tools/notification.md
> [AUTO-PR] New content release -  2021-11-22T16:13:55.436Z

- content/en/blog/posts/explore-how-your-department-can-deliver-better-services.md
- content/fr/blog/posts/découvrez-comment-votre-ministère-peut-offrir-de-meilleurs-services.md
> [AUTO-PR] New content release -  2021-11-24T16:33:37.785Z

- content/en/blog/posts/explore-how-your-department-can-deliver-better-services.md
- content/fr/blog/posts/découvrez-comment-votre-ministère-peut-offrir-de-meilleurs-services.md
> [AUTO-PR] New content release -  2021-11-24T18:00:40.947Z

- content/en/careers/positions/executive-assistant.md
- content/fr/careers/positions/adjoint-e-de-direction.md
> [AUTO-PR] New content release -  2021-11-29T21:12:14.173Z

- content/en/careers/positions/executive-assistant---chief-operating-officer.md
- content/en/careers/positions/executive-assistant.md
- content/fr/careers/positions/adjoint-e-de-direction.md
- content/fr/careers/positions/adjoint·e-exécutif·ve---directeur-des-opérations.md
> [AUTO-PR] New content release -  2021-11-29T21:54:56.731Z

- layouts/partials/404.en.html
- layouts/partials/404.fr.html
> updates to 404 page

- assets/sass/cds/_nav.scss
Fix for the close button issue. The tabs were masking over the close button making it inaccessible. Fixed it by adding z index to the close button. Also fixed animation flicker when closing the modal.
> animation and close button fix

- assets/sass/cds/_sections.scss
Fixed double thick border issue:
Also removed margin from newsletter box.
> fixed borders

- layouts/partials/social-links.html
Formatting messed up some of the links. Quick fix.
https://gcdigital.slack.com/archives/CG00PTC5R/p1638477937114300
> fixed broken footer links

- static/js/search.js
Fix for new searches. Some times the previous search would not fully clear after pressing the close button.
> fix for new search

- layouts/_default/baseof.html
> GTM update

- layouts/_default/baseof.html
> reverted gtm ID

- layouts/partials/analytics.html
Updated the analytics.html file to remove the legacy tag
> analytics html update

- layouts/partials/mailing-list.html
Fixed issue with subscribe button.
> fixed form action

- data/team.yml
> [AUTO-PR] New content release -  2021-12-09T18:56:18.828Z

- i18n/en.yaml
- i18n/fr.yaml
- layouts/index.html
Updated the ID's to better track for Google Analytics
> translation for GTM

- content/en/careers/positions/interaction-designer-front-end-developer--ef1dd61a-bceb-42b5-9029-5cb139a9c12f.md
- content/fr/careers/positions/concepteur·trice-d’interaction-développeur·se-front-end--ef1dd61a-bceb-42b5-9029-5cb139a9c12f.md
> [AUTO-PR] New content release -  2021-12-17T17:11:21.930Z

- content/en/careers/positions/interaction-designer-front-end-developer--ef1dd61a-bceb-42b5-9029-5cb139a9c12f.md
- content/fr/careers/positions/concepteur·trice-d’interaction-développeur·se-front-end--ef1dd61a-bceb-42b5-9029-5cb139a9c12f.md
> [AUTO-PR] New content release -  2021-12-21T22:47:24.856Z

- content/en/careers/positions/interaction-designer--ef1dd61a-bceb-42b5-9029-5cb139a9c12f.md
- content/fr/careers/positions/concepteur·trice-d’interaction---ef1dd61a-bceb-42b5-9029-5cb139a9c12f.md
> [AUTO-PR] New content release -  2022-01-04T17:25:35.189Z

- data/team.yml
> [AUTO-PR] New content release -  2022-01-05T15:35:36.011Z

- content/en/careers/positions/interaction-designer--ef1dd61a-bceb-42b5-9029-5cb139a9c12f.md
- content/fr/careers/positions/concepteur·trice-d’interaction---ef1dd61a-bceb-42b5-9029-5cb139a9c12f.md
> [AUTO-PR] New content release -  2022-01-07T18:58:50.567Z

- content/en/careers/positions/senior-front-end-developer--ebf0d33e-0343-4ee3-9f0d-e00401bb4a20.md
- content/fr/careers/positions/développeur·se-principal·e-de-logiciels-frontaux--ebf0d33e-0343-4ee3-9f0d-e00401bb4a20.md
> [AUTO-PR] New content release -  2022-01-07T22:29:59.766Z

- layouts/_default/baseof.html
Added google optimize tag for A/B Testing
> added google optimize tag

- content/en/careers/positions/senior-policy-advisor--289adf15-22f1-44fb-885c-3b2ea720183b.md
- content/fr/careers/positions/conseiller-ère-principal-e-en-politique--289adf15-22f1-44fb-885c-3b2ea720183b.md
- data/team.yml
> [AUTO-PR] New content release -  2022-01-18T20:35:50.272Z

- content/en/careers/positions/senior-policy-advisor--289adf15-22f1-44fb-885c-3b2ea720183b.md
- content/fr/careers/positions/conseiller-ère-principal-e-en-politique--289adf15-22f1-44fb-885c-3b2ea720183b.md
> [AUTO-PR] New content release -  2022-01-20T14:59:48.695Z

- data/team.yml
> [AUTO-PR] New content release -  2022-01-21T15:56:54.005Z

- data/team.yml
> [AUTO-PR] New content release -  2022-01-21T16:11:07.736Z

- content/en/careers/positions/senior-application-security-developer--f86269be-5bdc-45ca-89b6-a701377524a0.md
- content/fr/careers/positions/développeur-développeuse-principal.e-de-la-sécurité-des-applications--f86269be-5bdc-45ca-89b6-a701377524a0.md
> [AUTO-PR] New content release -  2022-01-21T20:01:35.643Z

- content/en/careers/positions/senior-application-security-developer--f86269be-5bdc-45ca-89b6-a701377524a0.md
- content/fr/careers/positions/développeur-développeuse-principal.e-de-la-sécurité-des-applications--f86269be-5bdc-45ca-89b6-a701377524a0.md
> [AUTO-PR] New content release -  2022-01-24T18:05:32.001Z

- content/en/careers/positions/senior-application-security-developer--f86269be-5bdc-45ca-89b6-a701377524a0.md
> [AUTO-PR] New content release -  2022-01-26T14:21:01.959Z

- content/en/careers/positions/people-operations-coordinator--272a1ae2-b8ca-4fec-b954-2da30b0f24a7.md
- content/fr/careers/positions/coordonnateur-coordonnatrice-des-opérations-du-personnel--272a1ae2-b8ca-4fec-b954-2da30b0f24a7.md
> [AUTO-PR] New content release -  2022-02-02T18:05:32.033Z

- content/en/careers/positions/senior-policy-advisor--289adf15-22f1-44fb-885c-3b2ea720183b.md
- content/fr/careers/positions/conseiller-ère-principal-e-en-politique--289adf15-22f1-44fb-885c-3b2ea720183b.md
> [AUTO-PR] New content release -  2022-02-04T22:28:19.426Z

- content/en/guides/resources/accessibility-handbook.md
- content/en/guides/resources/an-introduction-to-digital-government.md
- content/en/guides/resources/documentation-book-a-government-appointment.md
- content/en/guides/resources/product-evaluation-framework.md
- content/en/guides/resources/research-interviewing-guide.md
- content/en/guides/resources/usability-testing-guide.md
- content/en/product-suite/product/publish-and-manage-online-forms.md
- content/en/product-suite/product/send-automated-emails-and-text-notifications.md
- content/fr/guides/resources/cadre-d’évaluation-de-produits.md
- content/fr/guides/resources/documentation-prendre-rendez-vous-pour-un-service-gouvernemental.md
- content/fr/guides/resources/guide-des-entrevues-de-recherche.md
- content/fr/guides/resources/guide-des-tests-d'utilisabilité.md
- content/fr/guides/resources/introduction-au-gouvernement-numérique.md
- content/fr/guides/resources/manuel-d’accessibilité-du-snc.md
- content/fr/product-suite/product/envoyez-des-courriels-et-des-messages-texte-automatisés.md
- content/fr/product-suite/product/publiez-et-gérez-des-formulaires-en-ligne.md
> [AUTO-PR] New content release -  2022-02-07T16:02:33.132Z

- content/en/product-suite/product/publish-and-manage-online-forms.md
- content/en/product-suite/product/send-automated-emails-and-text-notifications.md
- content/fr/product-suite/product/envoyez-des-courriels-et-des-messages-texte-automatisés.md
- content/fr/product-suite/product/publiez-et-gérez-des-formulaires-en-ligne.md
> [AUTO-PR] New content release -  2022-02-08T19:42:04.006Z

- content/en/blog/posts/are-you-the-canadian-digital-service’s-next-ceo?.md
- content/en/guides/resources/accessibility-handbook.md
- content/en/guides/resources/an-introduction-to-digital-government.md
- content/en/guides/resources/documentation-book-a-government-appointment.md
- content/en/guides/resources/product-evaluation-framework.md
- content/en/guides/resources/research-interviewing-guide.md
- content/en/guides/resources/usability-testing-guide.md
- content/en/product-suite/product/publish-and-manage-online-forms.md
- content/fr/blog/posts/êtes-vous-notre-pdg-de-demain?.md
- content/fr/guides/resources/cadre-d’évaluation-de-produits.md
- content/fr/guides/resources/documentation-prendre-rendez-vous-pour-un-service-gouvernemental.md
- content/fr/guides/resources/guide-des-entrevues-de-recherche.md
- content/fr/guides/resources/guide-des-tests-d'utilisabilité.md
> [AUTO-PR] New content release -  2022-02-14T16:53:54.708Z

- content/en/blog/posts/are-you-the-canadian-digital-service’s-next-ceo?.md
- content/fr/blog/posts/êtes-vous-notre-pdg-de-demain?.md
> [AUTO-PR] New content release -  2022-02-14T17:50:23.154Z

- content/en/blog/posts/are-you-the-canadian-digital-service’s-next-ceo?.md
> [AUTO-PR] New content release -  2022-02-14T19:38:08.669Z

- content/en/careers/positions/interaction-designer--ef1dd61a-bceb-42b5-9029-5cb139a9c12f.md
- content/en/guides/resources/documentation-for-booking-a-government-appointment.md
- content/fr/careers/positions/concepteur·trice-d’interaction---ef1dd61a-bceb-42b5-9029-5cb139a9c12f.md
- content/fr/guides/resources/instructions-pour-obtenir-un-rendez-vous-auprès-d’un-service-gouvernemental.md
> [AUTO-PR] New content release -  2022-02-14T21:43:11.917Z

- content/en/guides/resources/an-introduction-to-digital-government.md
- content/en/guides/resources/product-evaluation-framework.md
- content/en/guides/resources/research-interviewing-guide.md
- content/en/guides/resources/usability-testing-guide.md
- content/fr/guides/resources/cadre-d’évaluation-de-produits.md
- content/fr/guides/resources/guide-des-entrevues-de-recherche.md
- content/fr/guides/resources/guide-des-tests-d'utilisabilité.md
- content/fr/guides/resources/introduction-au-gouvernement-numérique.md
> [AUTO-PR] New content release -  2022-02-15T19:48:02.967Z

- content/en/statement-of-merit-criteria-ex5/_index.html
- content/fr/statement-of-merit-criteria-ex5/_index.html
- layouts/section/enonce-des-criteres-de-merite-ex5.html
- layouts/section/statement-of-merit-criteria-ex5.html
- Added an English and French webpage for the Statement of Merit Criteria (which will be linked in the upcoming CEO job posting going out Feb 24)
> English and French Statement of Merit Criteria for EX-05

- layouts/section/enonce-des-criteres-de-merite-ex5.html
Titre du poste : PDG
Groupe et niveau : EX-05
> Typo fixes on FR SOMC (EX-05)

- assets/sass/cds/_components.scss
- assets/sass/cds/_sections.scss
- config/_default/config.yaml
- content/en/coaching-and-advice/_index.html
- content/fr/coaching-and-advice/_index.html
- content/fr/spa-research.html
- i18n/en.yaml
- i18n/fr.yaml
- layouts/section/coaching-and-advice.html
- layouts/section/guides.html
- layouts/section/product-suite.html
Content update and redesign for Coaching and Advice page:
[Figma](https://www.figma.com/file/tkkBvItXhLQB6jDokbRfyp/the-REAL-CDS-Website-Revamp?node-id=2648%3A19368)
> coaching and advice redesign

- content/en/careers/positions/chief-executive-officer--5368b30c-eb29-405f-a449-78208c0a79bc.md
- content/fr/careers/positions/présidente-directrice-générale-ou-président-directeur-général--5368b30c-eb29-405f-a449-78208c0a79bc.md
> [AUTO-PR] New content release -  2022-03-09T19:53:59.272Z

- content/en/careers/positions/chief-executive-officer--5368b30c-eb29-405f-a449-78208c0a79bc.md
- content/fr/careers/positions/présidente-directrice-générale-ou-président-directeur-général--5368b30c-eb29-405f-a449-78208c0a79bc.md
> [AUTO-PR] New content release -  2022-03-09T23:39:59.162Z

- content/en/careers/positions/chief-executive-officer--5368b30c-eb29-405f-a449-78208c0a79bc.md
- content/fr/careers/positions/présidente-directrice-générale-ou-président-directeur-général--5368b30c-eb29-405f-a449-78208c0a79bc.md
> [AUTO-PR] New content release -  2022-03-10T14:10:25.527Z

- content/en/careers/positions/senior-front-end-developer--ebf0d33e-0343-4ee3-9f0d-e00401bb4a20.md
- content/fr/careers/positions/développeur·se-principal·e-de-logiciels-frontaux--ebf0d33e-0343-4ee3-9f0d-e00401bb4a20.md
> [AUTO-PR] New content release -  2022-03-10T22:03:26.265Z

- content/en/careers/positions/communications-assistant--e69735e7-dc01-4004-a5e1-d079f9615ca7.md
- content/fr/careers/positions/assistant-ou-assistante-en-communications--e69735e7-dc01-4004-a5e1-d079f9615ca7.md
> [AUTO-PR] New content release -  2022-03-17T13:02:13.275Z

- content/en/careers/positions/communications-assistant--e69735e7-dc01-4004-a5e1-d079f9615ca7.md
> [AUTO-PR] New content release -  2022-03-17T13:41:02.629Z

- content/en/careers/positions/communications-assistant--e69735e7-dc01-4004-a5e1-d079f9615ca7.md
- content/fr/careers/positions/assistant-ou-assistante-en-communications--e69735e7-dc01-4004-a5e1-d079f9615ca7.md
> [AUTO-PR] New content release -  2022-03-18T13:13:38.440Z

- content/en/blog/posts/a-faster-way-to-create-privacy-and-consent-notices-in-government.md
- content/en/careers/positions/consulting-digital-practitioner---devsecops--c00d0402-56cd-49b3-9d37-525b9fd31cfd.md
- content/en/careers/positions/consulting-digital-practitioner---research-and-service-design--09bc4216-04f8-4e70-b2af-be70e6bc3c9c.md
- content/fr/careers/positions/praticien-du-numérique-chargé-de-la-consultation-ou-praticienne-du-numérique-chargée-de-la-consultation---recherche-en-conception-et-conception-de-services---09bc4216-04f8-4e70-b2af-be70e6bc3c9c.md
- content/fr/careers/positions/praticien-du-numérique-chargé-de-la-consultation-ou-praticienne-du-numérique-chargée-de-la-consultation---sécurité-des-opérations-de-développement--c00d0402-56cd-49b3-9d37-525b9fd31cfd.md
> [AUTO-PR] New content release -  2022-03-22T16:56:59.458Z

- data/team.yml
> [AUTO-PR] New content release -  2022-03-22T17:49:26.119Z

- content/en/careers/positions/communications-assistant--e69735e7-dc01-4004-a5e1-d079f9615ca7.md
- content/fr/careers/positions/assistant-ou-assistante-en-communications--e69735e7-dc01-4004-a5e1-d079f9615ca7.md
> [AUTO-PR] New content release -  2022-03-22T19:44:39.190Z

- data/team.yml
> [AUTO-PR] New content release -  2022-03-30T17:44:32.272Z

- content/en/our-values.html
- content/fr/our-values.html
Updated the content one of the cards on our values page.
https://digital-cana-update-gui-ww9zcb.herokuapp.com/our-values/
> updated our values page

- content/en/blog/posts/how-a-new-directive-makes-it-easier-to-procure-software-in-the-gc.md
- content/fr/blog/posts/comment-une-nouvelle-directive-simplifie-l’obtention-de-logiciels-pour-le-gouvernement-du-canada.md
> [AUTO-PR] New content release -  2022-03-31T17:15:15.584Z

- content/en/form-submission/error.md
Small issue that hid the language toggle on the error page
> fixed issue with lang toggle on error page

- content/en/careers/positions/consulting-digital-practitioner---devsecops--c00d0402-56cd-49b3-9d37-525b9fd31cfd.md
- content/en/careers/positions/consulting-digital-practitioner---research-and-service-design--09bc4216-04f8-4e70-b2af-be70e6bc3c9c.md
- content/en/careers/positions/senior-application-security-developer--f86269be-5bdc-45ca-89b6-a701377524a0.md
- content/fr/careers/positions/développeur-développeuse-principal.e-de-la-sécurité-des-applications--f86269be-5bdc-45ca-89b6-a701377524a0.md
- content/fr/careers/positions/praticien-du-numérique-chargé-de-la-consultation-ou-praticienne-du-numérique-chargée-de-la-consultation---recherche-en-conception-et-conception-de-services---09bc4216-04f8-4e70-b2af-be70e6bc3c9c.md
- content/fr/careers/positions/praticien-du-numérique-chargé-de-la-consultation-ou-praticienne-du-numérique-chargée-de-la-consultation---sécurité-des-opérations-de-développement--c00d0402-56cd-49b3-9d37-525b9fd31cfd.md
> [AUTO-PR] New content release -  2022-04-01T12:29:51.299Z

- data/team.yml
> [AUTO-PR] New content release -  2022-04-01T19:56:06.704Z

- data/team.yml
> [AUTO-PR] New content release -  2022-04-01T20:40:35.534Z

- layouts/section/job-posting.en.html
- layouts/section/job-posting.fr.html
Fixed issue that caused repeating job titles
> fixed issue with repeating job title

- data/team.yml
> [AUTO-PR] New content release -  2022-04-04T16:17:27.475Z

- content/en/careers/positions/senior-stakeholder-relations-advisor---strategic-engagement--685e34db-a7c9-4476-bc60-ae1c1e751763.md
- content/fr/careers/positions/conseiller-ère-principal-e-en-relations-avec-les-parties-prenantes--685e34db-a7c9-4476-bc60-ae1c1e75176.md
> [AUTO-PR] New content release -  2022-04-04T16:37:34.796Z

- content/en/blog/posts/reflections-on-a-service-at-100-weeks.md
- content/fr/blog/posts/réflexions-sur-un-service-au-bout-de-100-semaines.md
> [AUTO-PR] New content release -  2022-04-05T12:54:08.297Z

- content/en/careers/positions/senior-stakeholder-relations-advisor---strategic-engagement--685e34db-a7c9-4476-bc60-ae1c1e751763.md
- content/fr/careers/positions/conseiller-ère-principal-e-en-relations-avec-les-parties-prenantes--685e34db-a7c9-4476-bc60-ae1c1e75176.md
> [AUTO-PR] New content release -  2022-04-06T18:20:18.764Z

- data/team.yml
> [AUTO-PR] New content release -  2022-04-07T17:28:25.191Z

- data/team.yml
> [AUTO-PR] New content release -  2022-04-07T18:00:34.300Z

- content/fr/careers/positions/conseiller-ère-principal-e-en-relations-avec-les-parties-prenantes--685e34db-a7c9-4476-bc60-ae1c1e751763.md
> [AUTO-PR] New content release -  2022-04-08T16:19:20.061Z

- content/en/careers/positions/senior-stakeholder-relations-advisor---strategic-engagement--685e34db-a7c9-4476-bc60-ae1c1e751763.md
- content/fr/careers/positions/conseiller-ère-principal-e-en-relations-avec-les-parties-prenantes--685e34db-a7c9-4476-bc60-ae1c1e751763.md
> [AUTO-PR] New content release -  2022-04-14T14:41:07.035Z

- content/en/blog/posts/toxic-or-positive-masculinity?-how-men-can-shift-workplace-culture.md
- content/fr/blog/posts/la-masculinité-positive-ou-toxique-:-comment-les-hommes-peuvent-transformer-la-culture-organisationnelle.md
> [AUTO-PR] New content release -  2022-04-20T18:45:11.277Z

- content/en/careers/positions/technical-support-developer--231fd144-b6ca-4278-9667-adb6f62b869f.md
- content/fr/careers/positions/développeur-de-soutien--231fd144-b6ca-4278-9667-adb6f62b869f.md
> [AUTO-PR] New content release -  2022-04-21T16:35:05.361Z

- content/fr/careers/positions/développeur-ou-développeuse-du-soutien-technique--231fd144-b6ca-4278-9667-adb6f62b869f.md
> [AUTO-PR] New content release -  2022-04-21T16:47:36.159Z

- content/en/blog/posts/toxic-or-positive-masculinity?-how-men-can-shift-workplace-culture.md
- content/fr/careers/positions/développeur-ou-développeuse-du-soutien-technique--231fd144-b6ca-4278-9667-adb6f62b869f.md
> [AUTO-PR] New content release -  2022-04-21T17:30:33.950Z

- content/en/careers/positions/technical-support-developer--231fd144-b6ca-4278-9667-adb6f62b869f.md
> [AUTO-PR] New content release -  2022-04-21T18:02:33.966Z

- layouts/section/meet-the-team.html
Sorted Community categories alphabetically.
> sorted meet the team page

- content/en/careers/positions/visual-storytelling-advisor--79bcb51a-f5dc-4a33-be6e-66a53130c25e.md
- content/fr/careers/positions/conseiller-en-narration-visuelle--79bcb51a-f5dc-4a33-be6e-66a53130c25e.md
> [AUTO-PR] New content release -  2022-04-25T19:48:59.684Z

- data/team.yml
> [AUTO-PR] New content release -  2022-05-02T14:54:08.765Z

- data/team.yml
> [AUTO-PR] New content release -  2022-05-02T17:49:27.091Z

- data/team.yml
> [AUTO-PR] New content release -  2022-05-02T19:10:42.926Z

- content/en/careers/positions/technical-support-developer--231fd144-b6ca-4278-9667-adb6f62b869f.md
- content/fr/careers/positions/développeur-ou-développeuse-du-soutien-technique--231fd144-b6ca-4278-9667-adb6f62b869f.md
> [AUTO-PR] New content release -  2022-05-06T16:51:10.297Z

- content/en/careers/positions/consulting-digital-practitioner---research-and-service-design--09bc4216-04f8-4e70-b2af-be70e6bc3c9c.md
- content/fr/careers/positions/praticien-du-numérique-chargé-de-la-consultation-ou-praticienne-du-numérique-chargée-de-la-consultation---recherche-en-conception-et-conception-de-services---09bc4216-04f8-4e70-b2af-be70e6bc3c9c.md
> [AUTO-PR] New content release -  2022-05-09T14:20:59.548Z

- content/en/careers/positions/senior-project-services-advisor--df2507ec-8d24-487e-9617-2aec5097a456.md
> [AUTO-PR] New content release -  2022-05-09T18:05:02.428Z

- data/team.yml
> [AUTO-PR] New content release -  2022-05-10T12:14:12.229Z

- layouts/index.json
- static/js/search.js
Fixed the issue that caused the "Thank you" and "Error" page to show up on search results
> removed thank you, error from search

- i18n/fr.yaml
Quick fix to add ? in french search bar
> added ? in french search

- content/en/blog/posts/how-to-thoughtfully-name-government-services.md
- content/fr/blog/posts/comment-nommer-avec-soin-les-services-gouvernementaux.md
> [AUTO-PR] New content release -  2022-05-27T12:07:29.522Z

- content/en/blog/posts/how-to-thoughtfully-name-government-services.md
> [AUTO-PR] New content release -  2022-05-27T19:19:34.507Z

- content/en/blog/posts/how-to-thoughtfully-name-government-services.md
> [AUTO-PR] New content release -  2022-06-06T14:22:28.873Z

- content/en/careers/positions/content-designer--e28b029a-9d1a-4217-aece-c45cab0ed56d.md
- content/fr/careers/positions/concepteur-ou-conceptrice-de-contenu--e28b029a-9d1a-4217-aece-c45cab0ed56d.md
> [AUTO-PR] New content release -  2022-06-06T14:49:05.167Z

- content/en/careers/positions/content-designer--e28b029a-9d1a-4217-aece-c45cab0ed56d.md
- content/fr/careers/positions/concepteur-ou-conceptrice-de-contenu--e28b029a-9d1a-4217-aece-c45cab0ed56d.md
> [AUTO-PR] New content release -  2022-06-06T14:49:05.444Z

- data/team.yml
> [AUTO-PR] New content release -  2022-06-07T18:01:13.262Z

- data/team.yml
> [AUTO-PR] New content release -  2022-06-07T19:31:48.203Z

- data/team.yml
> [AUTO-PR] New content release -  2022-06-07T20:29:35.037Z

- data/team.yml
> [AUTO-PR] New content release -  2022-06-08T17:40:22.968Z

- assets/sass/cds/_components.scss
- layouts/section/job-posting.en.html
- layouts/section/job-posting.fr.html
[EN](https://eo3j4qo75icgb6lpwcnieckney0oftfo.lambda-url.ca-central-1.on.aws/careers/positions/consulting-digital-practitioner-devsecops-c00d0402-56cd-49b3-9d37-525b9fd31cfd/)
[FR](https://xw47focxfg4kmoapixhia62xvi0zbolr.lambda-url.ca-central-1.on.aws/careers/positions/concepteur-ou-conceptrice-de-contenu-e28b029a-9d1a-4217-aece-c45cab0ed56d/)
> removed duplicate text

- content/en/careers/positions/bilingual-technical-recruiter--e5d452ed-eff5-4927-b4f9-fd488a6a0508.md
- content/fr/careers/positions/recruteur-technique-recruteuse-technique-bilingue--e5d452ed-eff5-4927-b4f9-fd488a6a0508.md
- data/team.yml
> [AUTO-PR] New content release -  2022-06-13T18:35:33.744Z

- content/en/careers/positions/bilingual-technical-recruiter--e5d452ed-eff5-4927-b4f9-fd488a6a0508.md
- content/fr/careers/positions/recruteur-technique-recruteuse-technique-bilingue--e5d452ed-eff5-4927-b4f9-fd488a6a0508.md
> [AUTO-PR] New content release -  2022-06-13T18:52:45.498Z

- content/en/careers/positions/bilingual-technical-recruiter--e5d452ed-eff5-4927-b4f9-fd488a6a0508.md
- content/fr/careers/positions/recruteur-technique-recruteuse-technique-bilingue--e5d452ed-eff5-4927-b4f9-fd488a6a0508.md
> [AUTO-PR] New content release -  2022-06-13T18:52:45.634Z

- content/en/a11y/_index.md
- content/en/a11y/accessibility-services-at-cds.md
- content/en/a11y/how-to-make-it-accessible.md
- content/en/a11y/our-commitment.md
- content/en/legal/privacy-notice.html
- content/en/legal/privacy.html
Sentence Case updates
[Privacy](https://iudyp6rsqwh33m5klo5kqhvs2a0antez.lambda-url.ca-central-1.on.aws/legal/privacy/)
[Privacy Notice](https://iudyp6rsqwh33m5klo5kqhvs2a0antez.lambda-url.ca-central-1.on.aws/legal/privacy-notice/)
[A11y Handbook](https://iudyp6rsqwh33m5klo5kqhvs2a0antez.lambda-url.ca-central-1.on.aws/a11y/)
> updated content

- content/en/products/products/government-of-canada-exposure-notifications-mobile-app.md
- content/fr/products/products/application-mobile-de-notification-d’exposition-du-gouvernement-du-canada.md
> [AUTO-PR] New content release -  2022-06-17T17:16:06.458Z

- content/en/products/products/government-of-canada-exposure-notifications-mobile-app.md
- content/fr/products/products/application-mobile-de-notification-d’exposition-du-gouvernement-du-canada.md
> [AUTO-PR] New content release -  2022-06-17T17:31:17.657Z

- content/en/products/products/e-briefing-app.md
- content/en/products/products/energuide-api.md
- content/en/products/products/find-financial-help-during-covid-19.md
- content/en/products/products/find-relevant-benefits-for-veterans.md
- content/en/products/products/guidance-on-regulatory-consultation.md
- content/en/products/products/help-canadians-access-the-cpp-disability-benefit.md
- content/en/products/products/help-canadians-with-low-income-file-taxes.md
- content/en/products/products/impact-canada-challenge-platform.md
- content/en/products/products/make-it-easier-to-identify-tender-opportunities.md
- content/en/products/products/open-call-catalogue-to-help-governments-respond-to-covid-19.md
- content/en/products/products/report-a-cybercrime.md
- content/en/products/products/reschedule-a-citizenship-test.md
- content/en/products/products/track-web-security-compliance.md
- content/fr/products/products/aider-les-canadiennes-et-les-canadiens-à-recevoir-des-prestations-d’invalidité-du-rpc.md
- content/fr/products/products/aider-les-canadiens-à-faible-revenu-à-produire-leur-déclaration-fiscale.md
- content/fr/products/products/api-énerguide.md
- content/fr/products/products/application-de-breffage-électronique.md
- content/fr/products/products/faciliter-le-repérage-d’appels-d’offres.md
- content/fr/products/products/faire-des-recommandations-en-vue-des-consultations-sur-la-réglementation.md
- content/fr/products/products/le-catalogue-appel-ouvert-pour-aider-les-gouvernements-à-répondre-à-la-crise-de-la-covid-19.md
- content/fr/products/products/plateforme-de-défis-impact-canada.md
- content/fr/products/products/reporter-un-examen-de-citoyenneté.md
- content/fr/products/products/signaler-un-crime-informatique.md
- content/fr/products/products/suivre-ou-vérifier-la-confirmité-en-matière-de-sécurité-web.md
> [AUTO-PR] New content release -  2022-06-17T17:49:21.321Z

- content/en/blog/posts/a-faster-way-to-create-privacy-and-consent-notices-in-government.md
- content/en/careers/positions/director-of-talent-and-internal-operations--null.md
- content/fr/careers/positions/directeur·rice-des-opérations-internes-et-du-talent--null.md
- content/fr/products/products/trouver-les-prestations-pertinentes-pour-les-vétérans.md
- data/team.yml
> [AUTO-PR] New content release -  2022-06-21T13:47:28.315Z

- content/fr/blog/posts/les-rétrospectives-inclusives-:-dix-conseils-pour-devenir-une-meilleure-équipe!.md
> [AUTO-PR] New content release -  2022-06-21T17:55:50.354Z

- content/en/blog/posts/running-inclusive-retros:-10-tips-for-growing-as-a-team!.md
> [AUTO-PR] New content release -  2022-06-21T19:21:33.135Z

- content/en/careers/positions/senior-project-services-advisor--df2507ec-8d24-487e-9617-2aec5097a456.md
- content/fr/careers/positions/conseiller·ère-principal·e-en-services-de-projet---df2507ec-8d24-487e-9617-2aec5097a456.md
- data/team.yml
> [AUTO-PR] New content release -  2022-06-27T20:42:05.275Z

- layouts/section/guides.html
Updated Guides contact email address with the new one.
> updated email address

- content/en/blog/posts/empower-to-protect:-recalls-&-safety-alerts-in-canada.md
- content/fr/blog/posts/informer-pour-protéger-:-rappels-et-avis-de-sécurité-au-canada.md
> [AUTO-PR] New content release -  2022-07-04T15:50:09.978Z

- content/en/blog/posts/empower-to-protect:-recalls-&-safety-alerts-in-canada.md
- content/fr/blog/posts/informer-pour-protéger-:-rappels-et-avis-de-sécurité-au-canada.md
> [AUTO-PR] New content release -  2022-07-05T17:02:47.888Z

- content/en/careers/positions/director-of-talent-and-internal-operations--73bdecab-c9bd-4fa2-955f-8bca0787bcf4.md
- content/fr/careers/positions/directeur·rice-des-opérations-internes-et-du-talent--73bdecab-c9bd-4fa2-955f-8bca0787bcf4.md
> [AUTO-PR] New content release -  2022-07-07T21:37:55.112Z

- content/en/careers/positions/director-of-talent-and-internal-operations--73bdecab-c9bd-4fa2-955f-8bca0787bcf4.md
- content/fr/careers/positions/directeur·rice-des-opérations-internes-et-du-talent--73bdecab-c9bd-4fa2-955f-8bca0787bcf4.md
> [AUTO-PR] New content release -  2022-07-08T12:48:22.563Z

- content/en/careers/positions/senior-content-designer--a3772e8b-c531-4177-9227-1b1b0790243a.md
> [AUTO-PR] New content release -  2022-07-08T19:15:02.109Z

- content/en/careers/positions/content-designer--e28b029a-9d1a-4217-aece-c45cab0ed56d.md
- content/fr/careers/positions/concepteur-ou-conceptrice-de-contenu--e28b029a-9d1a-4217-aece-c45cab0ed56d.md
> [AUTO-PR] New content release -  2022-07-08T19:28:44.338Z

- content/en/blog/posts/helping-people-find-content:-how-to-build-a-website-search-bar.md
- content/fr/blog/posts/aider-les-gens-à-trouver-du-contenu-:-comment-créer-une-barre-de-recherche-sur-un-site-web.md
> [AUTO-PR] New content release -  2022-07-14T13:34:32.898Z

- .github/workflows/build-test.yml
Updated htmlproofer options to reflect changes in v4
> updated build test

- content/en/blog/posts/building-for-learning-and-iteration-with-our-web-search-bar.md
- content/en/blog/posts/helping-people-find-content:-how-to-build-a-website-search-bar.md
- content/en/blog/posts/how-to-thoughtfully-name-government-services.md
- content/en/careers/positions/consulting-digital-practitioner:-content-design--4ed86217-573b-4364-8b59-b8c0d6498b06.md
- content/fr/blog/posts/comment-nommer-avec-soin-les-services-gouvernementaux.md
- content/fr/blog/posts/créer-avec-l’intention-d’apprendre-et-de-s’améliorer-:-le-cas-de-notre-barre-de-recherche.md
- content/fr/careers/positions/praticienne-du-numérique-chargée-de-la-consultation-ou-praticien-du-numérique-chargé-de-la-consultation-:-conception-de-contenu--4ed86217-573b-4364-8b59-b8c0d6498b06.md
> [AUTO-PR] New content release -  2022-07-25T13:54:03.206Z

- content/fr/careers/positions/praticienne-du-numérique-chargée-de-la-consultation-ou-praticien-du-numérique-chargé-de-la-consultation-:-conception-de-contenu--4ed86217-573b-4364-8b59-b8c0d6498b06.md
- data/team.yml
> [AUTO-PR] New content release -  2022-07-25T14:07:47.682Z

- content/en/blog/posts/building-for-learning-and-iteration-with-our-web-search-bar.md
- content/fr/blog/posts/créer-avec-l’intention-d’apprendre-et-de-s’améliorer-:-le-cas-de-notre-barre-de-recherche.md
> [AUTO-PR] New content release -  2022-07-28T13:36:50.047Z

- data/team.yml
> [AUTO-PR] New content release -  2022-07-28T19:08:00.714Z

- layouts/partials/meet-the-team-partials.html
Fetching from GC Articles, team members images do not have a hash value. Added a condition to get the value of image if imagehash is empty or nil. This will likely change when we port over users to gc articles.
> added condition if imagehas is nil

- data/team.yml
> [AUTO-PR] New content release -  2022-08-11T14:05:25.623Z

- content/en/careers/positions/technical-operations-analyst--27342ded-7532-417e-940a-3bfdfe260043.md
- content/fr/careers/positions/analyste-des-opérations-techniques--27342ded-7532-417e-940a-3bfdfe260043.md
> [AUTO-PR] New content release -  2022-08-16T18:46:39.381Z

- content/fr/careers/positions/analyste-des-opérations-techniques--27342ded-7532-417e-940a-3bfdfe260043.md
> [AUTO-PR] New content release -  2022-08-16T19:05:29.433Z

- content/en/blog/posts/5-tips-to-make-your-presentations-sparkle.md
- content/fr/blog/posts/5-conseils-pour-faire-de-vos-présentations-de-véritables-bijoux.md
> [AUTO-PR] New content release -  2022-08-18T12:42:33.940Z

- content/en/careers/positions/senior-application-security-developer--db500188-4fab-4e1d-95de-0b3a3610fa57.md
- content/fr/careers/positions/développeur-développeuse-principal.e-de-la-sécurité-des-applications--db500188-4fab-4e1d-95de-0b3a3610fa57.md
> [AUTO-PR] New content release -  2022-08-18T17:13:05.688Z

- content/en/careers/positions/director-of-talent-and-internal-operations--73bdecab-c9bd-4fa2-955f-8bca0787bcf4.md
- content/fr/careers/positions/directeur·rice-des-opérations-internes-et-du-talent--73bdecab-c9bd-4fa2-955f-8bca0787bcf4.md
> [AUTO-PR] New content release -  2022-08-23T12:45:50.596Z

- data/team.yml
> [AUTO-PR] New content release -  2022-08-24T12:49:05.422Z

- content/en/careers/positions/bilingual-technical-recruiter--e5d452ed-eff5-4927-b4f9-fd488a6a0508.md
- content/en/careers/positions/technical-operations-analyst--27342ded-7532-417e-940a-3bfdfe260043.md
- content/fr/careers/positions/analyste-des-opérations-techniques--27342ded-7532-417e-940a-3bfdfe260043.md
- content/fr/careers/positions/recruteur-technique-recruteuse-technique-bilingue--e5d452ed-eff5-4927-b4f9-fd488a6a0508.md
> [AUTO-PR] New content release -  2022-08-25T21:03:08.655Z

- data/team.yml
> [AUTO-PR] New content release -  2022-08-29T18:06:47.955Z

- content/en/blog/posts/‘security-snack-time’-at-cds.md
- content/fr/blog/posts/comment-nommer-avec-soin-les-services-gouvernementaux.md
- content/fr/blog/posts/« bouchées-de-sécurité »-au-snc.md
> [AUTO-PR] New content release -  2022-08-31T15:25:42.234Z

- content/en/careers/positions/french-content-designer--af998de5-68bf-4882-8397-d71f570c478e.md
- content/fr/careers/positions/concepteur-ou-conceptrice-de-contenu-en-français--af998de5-68bf-4882-8397-d71f570c478e.md
> [AUTO-PR] New content release -  2022-09-02T16:29:07.555Z

- content/en/blog/posts/‘security-snack-time’-at-cds.md
- content/fr/blog/posts/« bouchées-de-sécurité »-au-snc.md
> [AUTO-PR] New content release -  2022-09-12T12:56:16.213Z

- data/team.yml
> [AUTO-PR] New content release -  2022-09-13T20:43:37.061Z

- content/en/careers/positions/consulting-digital-practitioner:-content-design--4ed86217-573b-4364-8b59-b8c0d6498b06.md
- content/en/careers/positions/senior-content-designer--a3772e8b-c531-4177-9227-1b1b0790243a.md
- content/fr/careers/positions/concepteur-ou-conceptrice-de-contenu-senior--a3772e8b-c531-4177-9227-1b1b0790243a.md
- content/fr/careers/positions/praticienne-du-numérique-chargée-de-la-consultation-ou-praticien-du-numérique-chargé-de-la-consultation-:-conception-de-contenu--4ed86217-573b-4364-8b59-b8c0d6498b06.md
> [AUTO-PR] New content release -  2022-09-14T18:24:52.582Z

- data/team.yml
> [AUTO-PR] New content release -  2022-09-16T16:21:07.570Z

- data/team.yml
> [AUTO-PR] New content release -  2022-09-21T15:34:19.482Z

- data/team.yml
> [AUTO-PR] New content release -  2022-09-26T21:04:24.520Z

- data/team.yml
> [AUTO-PR] New content release -  2022-10-06T20:40:32.496Z

- data/team.yml
> [AUTO-PR] New content release -  2022-10-06T20:45:35.073Z

- data/team.yml
> [AUTO-PR] New content release -  2022-10-07T17:20:48.469Z

- content/en/blog/posts/‘a-percentage-of-perfection’:-incident-management-at-cds.md
- content/fr/blog/posts/« parfait-ou-presque »-:-gestion-d’incidents-au-snc.md
> [AUTO-PR] New content release -  2022-10-13T16:53:32.887Z

- content/en/blog/posts/-‘a-percentage-of-perfection’:-incident-management-at-cds.md
- content/fr/blog/posts/«-parfait-ou-presque-»-:-gestion-d’incidents-au-snc.md
> [AUTO-PR] New content release -  2022-10-13T18:59:39.444Z

- content/en/blog/posts/-‘a-percentage-of-perfection’:-incident-management-at-cds.md
- content/fr/blog/posts/«-parfait-ou-presque-»-:-gestion-d’incidents-au-snc.md
> [AUTO-PR] New content release -  2022-10-13T20:00:44.719Z

- data/team.yml
> [AUTO-PR] New content release -  2022-10-20T19:08:10.489Z

- data/team.yml
> [AUTO-PR] New content release -  2022-10-20T19:14:54.367Z

- data/team.yml
> [AUTO-PR] New content release -  2022-10-21T18:09:29.670Z

- content/en/careers/positions/consulting-digital-practitioner---devsecops--c00d0402-56cd-49b3-9d37-525b9fd31cfd.md
- content/fr/careers/positions/praticien-du-numérique-chargé-de-la-consultation-ou-praticienne-du-numérique-chargée-de-la-consultation---sécurité-des-opérations-de-développement--c00d0402-56cd-49b3-9d37-525b9fd31cfd.md
> [AUTO-PR] New content release -  2022-10-25T14:38:03.230Z

- data/team.yml
> [AUTO-PR] New content release -  2022-10-31T13:07:53.260Z

- content/en/blog/posts/storytelling-resource-for-‘cooking-up-a-[blog]-storm’!.md
- content/fr/blog/posts/ressources-de-narration-:-rédigez-pour-régaler!.md
> [AUTO-PR] New content release -  2022-10-31T18:21:02.111Z

- content/en/blog/posts/storytelling-resource-for-‘cooking-up-a-[blog]-storm’!.md
- content/fr/blog/posts/ressources-de-narration-:-rédigez-pour-régaler!.md
> [AUTO-PR] New content release -  2022-10-31T18:46:00.687Z

- content/fr/blog/posts/ressources-de-narration-:-rédigez-pour-régaler!.md
> [AUTO-PR] New content release -  2022-10-31T19:00:52.508Z

- content/en/blog/posts/storytelling-resource-for-‘cooking-up-a-[blog]-storm’!.md
- content/fr/blog/posts/ressources-de-narration-:-rédigez-pour-régaler!.md
- data/team.yml
> [AUTO-PR] New content release -  2022-11-02T19:42:26.123Z

- data/team.yml
> [AUTO-PR] New content release -  2022-11-03T18:14:41.751Z

- assets/sass/cds/_sections.scss
- layouts/section/coaching-and-advice.html
- layouts/section/product-suite.html
Updated checkmark colour on the coaching and advice page
> changed checkmark colours

- content/en/blog/posts/working-in-the-open-with-a-sense-of-humility-and-community.md
- content/fr/blog/posts/travailler-ouvertement-avec-un-sentiment-d’humilité-et-de-communauté.md
> [AUTO-PR] New content release -  2022-11-21T13:53:04.584Z

- content/en/blog/posts/advice-informed-by-experience:-working-with-the-consulting-team-at-cds.md
- content/fr/blog/posts/des-conseils-éclairés-par-l’expérience-:-la-collaboration-avec-l’équipe-de-conseil-au-snc.md
> [AUTO-PR] New content release -  2022-11-24T15:58:40.265Z

- content/fr/blog/posts/des-conseils-éclairés-par-l’expérience-:-la-collaboration-avec-l’équipe-de-conseil-au-snc.md
> [AUTO-PR] New content release -  2022-11-24T16:17:06.100Z

- content/en/careers/positions/senior-infrastructure-developer--5ba20784-5f48-4281-a205-51ccb75568ca.md
- content/fr/careers/positions/développeur-principal-ou-développeuse-principale-de-l’infrastructure--5ba20784-5f48-4281-a205-51ccb75568ca.md
> [AUTO-PR] New content release -  2022-11-30T19:12:18.018Z

- content/en/careers/positions/senior-infrastructure-developer--5ba20784-5f48-4281-a205-51ccb75568ca.md
- content/fr/careers/positions/développeur-principal-ou-développeuse-principale-de-l’infrastructure--5ba20784-5f48-4281-a205-51ccb75568ca.md
> [AUTO-PR] New content release -  2022-12-06T18:59:33.934Z

- content/en/blog/posts/storytelling-resource-for-‘cooking-up-a-[blog]-storm’!.md
- content/fr/blog/posts/ressources-de-narration-:-rédigez-pour-régaler!.md
> [AUTO-PR] New content release -  2022-12-14T15:18:58.406Z

- static/.well-known/security.txt
This is to update https://digital.canada.ca/.well-known/security.txt
> bump the expiry date and re-sign

- content/en/blog/posts/improving-client-communications-using-gc-forms-and-gc-notify.md
- content/fr/blog/posts/améliorer-les-communications-avec-vos-clients-grâce-à-formulaires-gc-et-notification-gc.md
> [AUTO-PR] New content release -  2022-12-15T18:36:28.967Z

- content/en/blog/posts/improving-client-communications-using-gc-forms-and-gc-notify.md
> [AUTO-PR] New content release -  2022-12-15T18:50:58.408Z

- content/en/blog/posts/exploring-the-conditions-for-digital-service-delivery.md
- content/fr/product-suite/product/envoyez-des-courriels-et-des-messages-texte-automatisés.md
- content/fr/product-suite/product/publiez-et-gérez-des-formulaires-en-ligne.md
> [AUTO-PR] New content release -  2022-12-15T19:46:54.983Z

- content/en/blog/posts/improving-client-communications-using-gc-forms-and-gc-notify.md
- content/fr/blog/posts/améliorer-les-communications-avec-vos-clients-grâce-à-formulaires-gc-et-notification-gc.md
> [AUTO-PR] New content release -  2022-12-16T14:09:26.431Z

- content/fr/product-suite/product/envoyez-des-courriels-et-des-messages-texte-automatisés.md
- content/fr/product-suite/product/publiez-et-gérez-des-formulaires-en-ligne.md
> [AUTO-PR] New content release -  2022-12-16T14:20:29.281Z

- i18n/en.yaml
- i18n/fr.yaml
- layouts/partials/analytics.html
Migrating from Universal Analytics to GA4, Updated analytics.html to see if it is working correctly.
> added GA4 Code

- content/en/blog/posts/advice-informed-by-experience:-working-with-the-consulting-team-at-cds.md
- content/fr/blog/posts/améliorer-les-communications-avec-vos-clients-grâce-à-formulaires-gc-et-notification-gc.md
> [AUTO-PR] New content release -  2022-12-20T17:08:17.975Z

- content/en/careers/positions/research-operations-coordinator--6ac6d7f7-d80a-4f8c-9661-7ad35c3120f5.md
- content/fr/careers/positions/coordonnateur·rice-des-opérations-de-recherche--6ac6d7f7-d80a-4f8c-9661-7ad35c3120f5.md
> [AUTO-PR] New content release -  2022-12-21T15:34:07.744Z

- content/en/careers/positions/research-operations-coordinator--6ac6d7f7-d80a-4f8c-9661-7ad35c3120f5.md
> [AUTO-PR] New content release -  2022-12-21T16:42:40.523Z

- content/en/careers/positions/team-lead---gc-notify--9eaabc74-b860-4da5-96d6-18e9685b8139.md
- content/fr/careers/positions/chef-d’équipe---notification-gc--9eaabc74-b860-4da5-96d6-18e9685b8139.md
> [AUTO-PR] New content release -  2022-12-22T19:54:13.798Z

- content/en/careers/positions/senior-application-security-developer--db500188-4fab-4e1d-95de-0b3a3610fa57.md
- content/fr/careers/positions/développeur-développeuse-principal.e-de-la-sécurité-des-applications--db500188-4fab-4e1d-95de-0b3a3610fa57.md
> [AUTO-PR] New content release -  2023-01-04T15:04:22.618Z

- data/team.yml
> [AUTO-PR] New content release -  2023-01-06T18:52:03.399Z

- layouts/partials/analytics.html
> 1-3 sentence description of the changed you're proposing, including a link to
> a GitHub Issue # or Trello card if applicable.
---
> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.
> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.
---
> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de …
> reverted back to UA

- content/en/careers/positions/administrative-officer---internal-operations---878766da-0bed-4884-b61b-994597a90f0f.md
- content/fr/careers/positions/agent-administratif-ou-agente-administrative-—-opérations-internes--878766da-0bed-4884-b61b-994597a90f0f.md
> [AUTO-PR] New content release -  2023-01-12T19:31:21.530Z

- .github/workflows/build-test.yml
This PR adds a Github action that will track deployments of the website in Sentinel.
> Feat: Track deploys

- content/en/blog/posts/<strong>writing-privacy-notices-that-are-easy-to-read-and-understand<-strong>.md
- content/fr/blog/posts/<strong>rédiger-des-avis-de-confidentialité-faciles-à-lire-et-à-comprendre<-strong>.md
> [AUTO-PR] New content release -  2023-01-26T16:06:11.186Z

- content/en/blog/posts/-‘a-percentage-of-perfection’:-incident-management-at-cds.md
- content/en/blog/posts/writing-privacy-notices-that-are-easy-to-read-and-understand.md
- content/fr/blog/posts/rédiger-des-avis-de-confidentialité-faciles-à-lire-et-à-comprendre.md
> [AUTO-PR] New content release -  2023-01-26T20:09:43.283Z

- content/en/careers/positions/research-&-evaluation-analyst-partnerships-service-design-&-insights--d54d3c4c-3512-4d34-9260-e23e67a372f4.md
- content/fr/careers/positions/analyste-de-recherche-et-d’évaluation-conception-et-étude-de-services-de-partenariats--d54d3c4c-3512-4d34-9260-e23e67a372f4.md
> [AUTO-PR] New content release -  2023-01-31T21:03:36.977Z

- content/en/careers/positions/research-&-evaluation-analyst-partnerships-service-design-&-insights--d54d3c4c-3512-4d34-9260-e23e67a372f4.md
- content/fr/careers/positions/analyste-de-recherche-et-d’évaluation-conception-et-étude-de-services-de-partenariats--d54d3c4c-3512-4d34-9260-e23e67a372f4.md
> [AUTO-PR] New content release -  2023-01-31T22:10:19.000Z

- content/en/careers/positions/research-&-evaluation-analyst-partnerships-service-design-&-insights--d54d3c4c-3512-4d34-9260-e23e67a372f4.md
- content/fr/careers/positions/analyste-de-recherche-et-d’évaluation-conception-et-étude-de-services-de-partenariats--d54d3c4c-3512-4d34-9260-e23e67a372f4.md
> [AUTO-PR] New content release -  2023-01-31T22:19:07.190Z

- content/en/careers/positions/research-&-evaluation-analyst-partnerships-service-design-&-insights--d54d3c4c-3512-4d34-9260-e23e67a372f4.md
- content/fr/careers/positions/analyste-de-recherche-et-d’évaluation-conception-et-étude-de-services-de-partenariats--d54d3c4c-3512-4d34-9260-e23e67a372f4.md
> [AUTO-PR] New content release -  2023-02-01T13:13:06.698Z

- data/team.yml
> [AUTO-PR] New content release -  2023-02-01T15:19:49.011Z

- data/team.yml
> [AUTO-PR] New content release -  2023-02-01T15:32:23.073Z

- content/en/careers/positions/senior-infrastructure-developer--5ba20784-5f48-4281-a205-51ccb75568ca.md
- content/fr/careers/positions/développeur-principal-ou-développeuse-principale-de-l’infrastructure--5ba20784-5f48-4281-a205-51ccb75568ca.md
> [AUTO-PR] New content release -  2023-02-01T16:33:58.651Z

- content/en/careers/positions/research-&-evaluation-analyst-partnerships-service-design-&-insights--d54d3c4c-3512-4d34-9260-e23e67a372f4.md
- content/fr/careers/positions/analyste-de-recherche-et-d’évaluation-conception-et-étude-de-services-de-partenariats--d54d3c4c-3512-4d34-9260-e23e67a372f4.md
> [AUTO-PR] New content release -  2023-02-06T22:31:08.153Z

- content/en/careers/positions/research-&-evaluation-analyst-partnerships-service-design-&-insights--d54d3c4c-3512-4d34-9260-e23e67a372f4.md
- content/fr/careers/positions/analyste-de-recherche-et-d’évaluation-conception-et-étude-de-services-de-partenariats--d54d3c4c-3512-4d34-9260-e23e67a372f4.md
> [AUTO-PR] New content release -  2023-02-07T14:57:11.643Z

- content/en/blog/posts/storytelling-resource-for-‘cooking-up-a-[blog]-storm’!.md
> [AUTO-PR] New content release -  2023-02-08T20:52:20.219Z

- content/en/careers/positions/team-lead---gc-notify--9eaabc74-b860-4da5-96d6-18e9685b8139.md
- content/fr/careers/positions/chef-d’équipe---notification-gc--9eaabc74-b860-4da5-96d6-18e9685b8139.md
> [AUTO-PR] New content release -  2023-02-14T00:46:55.446Z

- content/en/product-suite/product/publish-and-manage-online-forms.md
- content/fr/product-suite/product/publiez-et-gérez-des-formulaires-en-ligne.md
> [AUTO-PR] New content release -  2023-02-15T18:05:21.743Z

- content/en/blog/posts/how-we’re-building-gc-forms:-our-4-accessible-approaches.md
- content/fr/blog/posts/comment-nous-concevons-formulaires-gc:-nos-quatre-approches-accessibles.md
> [AUTO-PR] New content release -  2023-02-16T16:20:43.143Z

- content/fr/blog/posts/parlons-de-l’expérience-utilisateur:-s’éloigner-des-pixels-se-tourner-vers-les-gens".md
> [AUTO-PR] New content release -  2023-02-27T15:32:04.963Z

- content/en/careers/positions/research-operations-coordinator--6ac6d7f7-d80a-4f8c-9661-7ad35c3120f5.md
- content/fr/careers/positions/coordonnateur·rice-des-opérations-de-recherche--6ac6d7f7-d80a-4f8c-9661-7ad35c3120f5.md
> [AUTO-PR] New content release -  2023-03-01T16:54:40.496Z

- data/team.yml
> [AUTO-PR] New content release -  2023-03-01T17:26:26.247Z

- data/team.yml
> [AUTO-PR] New content release -  2023-03-09T15:14:04.971Z

- content/en/legal/security-notice.html
- content/fr/blog/posts/lancement-d’un-service-alpha.md
- content/fr/legal/security-notice.html
https://github.com/cds-snc/digital-canada-ca/issues/4623
> Security notice URLs addition

- content/en/guides/resources/digital-government-learning-list.md
- content/fr/guides/resources/liste-d’apprentissage-du-gouvernement-numérique.md
> [AUTO-PR] New content release -  2023-03-15T18:41:17.632Z

- content/en/guides/resources/digital-government-learning-list.md
- content/fr/guides/resources/liste-d’apprentissage-du-gouvernement-numérique.md
> [AUTO-PR] New content release -  2023-03-15T19:15:11.244Z

- content/en/blog/posts/writing-without-excluding:-inclusivity-in-the-french-language.md
- content/fr/blog/posts/écrire-sans-exclure-:-l’inclusivité-en-langue-française.md
> [AUTO-PR] New content release -  2023-03-20T18:28:01.634Z

- content/en/blog/posts/three-years-of-data-driven-comms-for-“get-updates-on-covid-19”.md
- content/fr/blog/posts/obtenir-les-nouvelles-sur-la-covid-19 :-trois-années-de-communications-basées-sur-les-données.md
> [AUTO-PR] New content release -  2023-03-23T13:33:26.251Z

- content/en/guides/digital-reading-list.html
- content/fr/guides/digital-reading-list.html
Trying to do the redirects for reading list -> learning list
> add old files to redirect

- layouts/partials/analytics.html
> switched to ga4

- content/en/blog/posts/a-faster-way-to-create-privacy-and-consent-notices-in-government.md
- content/fr/blog/posts/des-avis-de-confidentialité-et-de-consentement-en-un-clin-d’œil.md
- data/team.yml
> [AUTO-PR] New content release -  2023-04-26T13:42:56.300Z

- data/team.yml
> [AUTO-PR] New content release -  2023-04-27T13:36:21.561Z

- content/en/blog/posts/listening-to-users:-moving-from-a-paper-based-process-to-a-digital-service.md
- content/fr/blog/posts/à-l’écoute-des-utilisateur·rice·s :-passer-d’un-processus-papier-à-un-service-numérique.md
> [AUTO-PR] New content release -  2023-05-04T19:20:57.418Z

- content/en/blog/posts/listening-to-users:-moving-from-a-paper-based-process-to-a-digital-service.md
> [AUTO-PR] New content release -  2023-05-04T19:29:44.898Z

- content/en/blog/posts/listening-to-users:-moving-from-a-paper-based-process-to-a-digital-service.md
- content/fr/blog/posts/à-l’écoute-des-utilisateur·rice·s :-passer-d’un-processus-papier-à-un-service-numérique.md
> [AUTO-PR] New content release -  2023-05-04T19:41:41.448Z

- content/en/blog/posts/listening-to-users:-moving-from-a-paper-based-process-to-a-digital-service.md
> [AUTO-PR] New content release -  2023-05-04T19:50:44.320Z

- .gitignore
- terragrunt/env/common/common_variables.tf
- terragrunt/env/common/provider.tf
- terragrunt/env/production/env_vars.hcl
- terragrunt/env/terragrunt.hcl
Added common variables, environment variables, added terragrunt file that takes care of adding remote state.
> updated hcl and common fles

- .github/workflows/tf_apply_production.yml
- .github/workflows/tf_plan_production.yml
- terragrunt/aws/s3/inputs.tf
- terragrunt/aws/s3/outputs.tf
- terragrunt/aws/s3/s3.tf
- terragrunt/env/production/s3/.terraform.lock.hcl
- terragrunt/env/production/s3/terragrunt.hcl
S3 module that will create the EN and FR s3 buckets that will hold all our content.
> added s3 module

- .github/workflows/tf_apply_production.yml
- .github/workflows/tf_plan_production.yml
- terragrunt/aws/hosted_zone/outputs.tf
- terragrunt/aws/hosted_zone/route53.tf
- terragrunt/env/production/hosted_zone/.terraform.lock.hcl
- terragrunt/env/production/hosted_zone/terragrunt.hcl
> added hosted zone module

- content/en/blog/posts/minding-the-[digital]-gender-gap-:-a-conversation-with-vic-chan.md
- content/fr/blog/posts/un-regard-sur-l’écart-[numérique]-entre-les-genres:-conversation-avec-vic-chan.md
> [AUTO-PR] New content release -  2023-06-08T15:13:12.849Z

- data/team.yml
> [AUTO-PR] New content release -  2023-06-12T11:45:11.315Z

- .github/workflows/tf_apply_production.yml
- .github/workflows/tf_plan_production.yml
- terragrunt/aws/cloudfront/certificates.tf
- terragrunt/aws/cloudfront/cloudfront.tf
- terragrunt/aws/cloudfront/iam.tf
- terragrunt/aws/cloudfront/inputs.tf
- terragrunt/aws/cloudfront/locals.tf
- terragrunt/aws/cloudfront/outputs.tf
- terragrunt/aws/cloudfront/s3.tf
- terragrunt/aws/cloudfront/waf.tf
- terragrunt/env/production/cloudfront/.terraform.lock.hcl
- terragrunt/env/production/cloudfront/terragrunt.hcl
Creation of the Cloudfront Module, WAF and S3 Logging bucket.
> added cloudfront module

- data/team.yml
> [AUTO-PR] New content release -  2023-06-14T20:25:00.264Z

- terragrunt/aws/cloudfront/waf.tf
Was running into a bug regarding with kinesis firehose for wafv2, updated name for it
> fixed waf logs name

- data/team.yml
> [AUTO-PR] New content release -  2023-06-16T13:22:22.888Z

- terragrunt/aws/s3/outputs.tf
Outputting s3 buckets to be used  in the cloudfront module to update bucket policy. Got stuck in a circular dependency cycle.
> output s3 modules

- content/en/blog/posts/how-gc-forms-can-help-collect-data-for-public-services.md
- content/fr/blog/posts/rédiger-des-avis-de-confidentialité-faciles-à-lire-et-à-comprendre.md
> [AUTO-PR] New content release -  2023-06-29T13:05:23.713Z

- content/en/blog/posts/how-gc-forms-can-help-collect-data-for-public-services.md
- content/fr/blog/posts/comment-formulaires-gc-peut-aider-à-recueillir-des-données-pour-les-services-publics.md
> [AUTO-PR] New content release -  2023-06-29T13:37:25.133Z

- data/team.yml
> [AUTO-PR] New content release -  2023-06-29T15:37:07.709Z

- data/team.yml
> [AUTO-PR] New content release -  2023-07-05T14:03:21.518Z

- content/en/blog/posts/5-tips-to-make-your-presentations-sparkle.md
- data/team.yml
> [AUTO-PR] New content release -  2023-07-24T13:22:37.555Z

- package-lock.json
- package.json
> removed snyk

- data/team.yml
> [AUTO-PR] New content release -  2023-07-28T13:40:48.886Z

- content/en/legal/security-notice.html
- content/fr/legal/security-notice.html
Updated the "report a vulnerability" form link to a new form with updated content.
> Fix update vulnerability form link

- content/en/blog/posts/inclusive-workplace-language:-being-more-thoughtful-about-the-words-we-use.md
- content/fr/blog/posts/langage-inclusif-au-travail-:-mieux-choisir-nos-mots.md
- data/team.yml
> [AUTO-PR] New content release -  2023-08-09T13:59:22.379Z

- layouts/section/careers.en.html
- layouts/section/careers.fr.html
When there are no activate postings, there will be a message displayed
[Figma](https://www.figma.com/file/tkkBvItXhLQB6jDokbRfyp/the-REAL-CDS-Website-Revamp?type=design&node-id=4819-30375&mode=design&t=Igvu2ZwSDrtJcF0t-0)
> updated en and fr careers page

- data/team.yml
> [AUTO-PR] New content release -  2023-08-11T18:06:34.824Z

- content/en/product-suite/product/publish-and-manage-online-forms.md
- content/fr/product-suite/product/publiez-et-gérez-des-formulaires-en-ligne.md
> [AUTO-PR] New content release -  2023-08-18T18:29:29.734Z

- content/en/products/products/help-canadians-with-low-income-file-taxes.md
- content/fr/products/products/aider-les-canadiens-à-faible-revenu-à-produire-leur-déclaration-fiscale.md
> [AUTO-PR] New content release -  2023-08-23T14:07:52.598Z

- content/en/blog/posts/how-gc-forms-can-help-collect-data-for-public-services.md
> [AUTO-PR] New content release -  2023-08-23T18:59:33.701Z

- content/fr/blog/posts/comment-formulaires-gc-peut-aider-à-recueillir-des-données-pour-les-services-publics.md
> [AUTO-PR] New content release -  2023-08-23T19:09:02.393Z

- content/en/blog/posts/how-gc-forms-can-help-collect-data-for-public-services.md
- content/en/blog/posts/minding-the-[digital]-gender-gap-:-a-conversation-with-vic-chan.md
- content/fr/blog/posts/comment-formulaires-gc-peut-aider-à-recueillir-des-données-pour-les-services-publics.md
> [AUTO-PR] New content release -  2023-09-06T19:08:41.173Z

- data/team.yml
> [AUTO-PR] New content release -  2023-09-12T18:26:11.978Z

- content/en/blog/posts/how-we’re-planning-more-useful-and-equitable-meetings.md
- content/fr/blog/posts/comment-nous-planifions-des-réunions-plus-utiles-et-équitables .md
> [AUTO-PR] New content release -  2023-09-14T17:26:44.606Z

- content/en/blog/posts/delivering-digital-learning:-a-conversation-with-eliane-dorval.md
- content/fr/blog/posts/offrir-de-l’apprentissage-numérique-:-une-conversation-avec-eliane-dorval.md
> [AUTO-PR] New content release -  2023-09-19T18:10:08.307Z

- content/fr/blog/posts/comment-nous-planifions-des-réunions-plus-utiles-et-équitables .md
> [AUTO-PR] New content release -  2023-09-20T17:16:36.505Z

- content/en/blog/posts/building-trust-and-understanding:-privacy-notices-and-usability-testing .md
- content/fr/blog/posts/instaurer-la-confiance-et-renforcer-la-compréhension :-avis-de-confidentialité-et-tests-d’utilisabilité.md
> [AUTO-PR] New content release -  2023-10-03T14:54:46.800Z

- content/en/careers/positions/apply-for-future-opportunities--77d1c499-8722-41ad-9985-e163d76b0e39.md
- content/fr/careers/positions/postulez-à-de-futures-offres-d’emploi---77d1c499-8722-41ad-9985-e163d76b0e39.md
> [AUTO-PR] New content release -  2023-10-03T20:15:49.567Z

- content/fr/blog/posts/offrir-de-l’apprentissage-numérique-:-une-conversation-avec-eliane-dorval.md
> [AUTO-PR] New content release -  2023-10-10T14:09:02.358Z

- content/en/blog/posts/mining-for-ideas-to-simplify-a-complex-process .md
> [AUTO-PR] New content release -  2023-10-12T13:34:54.905Z

- content/fr/blog/posts/une-mine-d’idées-pour-simplifier-un-processus-complexe.md
> [AUTO-PR] New content release -  2023-10-12T14:34:13.308Z

- content/en/careers/positions/apply-for-future-opportunities--77d1c499-8722-41ad-9985-e163d76b0e39.md
- content/fr/careers/positions/postulez-à-de-futures-offres-d’emploi---77d1c499-8722-41ad-9985-e163d76b0e39.md
> [AUTO-PR] New content release -  2023-10-18T16:47:21.087Z

- content/en/blog/posts/5-tips-to-make-your-presentations-sparkle.md
- content/en/careers/positions/share-your-resume--77d1c499-8722-41ad-9985-e163d76b0e39.md
- content/fr/careers/positions/envoyer-votre-c.v.--77d1c499-8722-41ad-9985-e163d76b0e39.md
> [AUTO-PR] New content release -  2023-10-18T20:27:33.356Z

- layouts/section/careers.en.html
- layouts/section/careers.fr.html
- layouts/section/job-posting.en.html
- layouts/section/job-posting.fr.html
Added evergreen job posting, and updated the careers page.
[Figma](https://www.figma.com/file/tkkBvItXhLQB6jDokbRfyp/the-REAL-CDS-Website-Revamp?type=design&node-id=4819-30394&mode=design&t=D0rhrAoXnZkviOkG-0)
> updated careers page

- data/team.yml
> [AUTO-PR] New content release -  2023-10-23T18:01:22.815Z

- content/en/legal/security-notice.html
- content/fr/legal/security-notice.html
Had to make small change to form settings (new URL generated after changes)
> minor updates to vulnerability report form

- content/en/legal/security-notice.html
- content/fr/legal/security-notice.html
> Update security notice content

- content/en/blog/posts/getting-cyber-safe-with-sherry-rumbolt.md
- content/fr/blog/posts/cap-sur-la-cybersécurité-avec-sherry rumbolt.md
> [AUTO-PR] New content release -  2023-10-30T15:11:33.505Z
